### ISSUE TITLE
i want to inject new line between error message.

### ISSUE THREAD

**Issue by ceo-mint-soft** [ghiscoding/angular-validation#100]
how can i?

**Comment by ghiscoding** [comment]
The error messages are concatenated and I won't change that behavior. So basically, there is no way of separating them and I will not change my code either. 

On the other hand, if you find the message to be too long, you could display only the last error. See the [Wiki - Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) with the option of `displayOnlyLastErrorMsg: true`

**Comment by ghiscoding** [comment]
If you want to make a pull request though, I might accept it... but I just don't want to spend time on this myself.

**Comment by ghiscoding** [comment]
Added a new [Global Option](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) named `errorMessageSeparator`, this separator is HTML based and so if you want a new line, you would use `<br/>`.

Your code could look like this:
```javascript
var vs = new validationService({ errorMessageSeparator: "<br/><li>" });
```

Please note that the Validation Summary will also contain the extra HTML code and to display proper HTML code with an `ngRepeat`, you will need to use `ngSanitize` and `ng-bind-html`

**Comment by ceo-mint-soft** [comment]
thanks ^^
