### ISSUE TITLE
How to validate on blur only?

### ISSUE THREAD

**Issue by shlomogoldstein** [ghiscoding/angular-validation#104]
How can I start validation only on blur of the input element? I know I can use ng model options. Is there an option already in your directive?
How can I globally enable to only validate on blur?

Using version "~1.4.14"

The problem is when validating an email address, the input is considered invalid while typing. I have switched debounce to 0 or 1000, it will validate while typing.

I am using this CSS also to display if invalid:

```
.ng-touched.ng-valid-validation + i.icon.error {
  display: none;
}

.ng-touched.ng-invalid-validation + i.icon.error {
  display: block;
}
```

Thank you very much for this directive. It is so fantastic.

**Comment by ghiscoding** [comment]
That's already the default way of validating, there's nothing to change. By default, it validates after x amount of time (debounce to 1000ms by default) OR if you blur the input it goes and validate right away. If you look at the [Plunker Demo](http://plnkr.co/jADq7H) on the email input, you'll see that effect

**Comment by shlomogoldstein** [comment]
I want to only validate on blur... So I guess I have to set debounce to 999999 ?

**Comment by ghiscoding** [comment]
Your assumptions are correct, there is no way currently to disable the validation while typing. Giving the `debounce` a high number will only wait a longer but will validate anyway unless a blur event occurred and if so will cancel the debounce timer.

**Comment by shlomogoldstein** [comment]
Even when setting ng-model-options='{ updateOn: "blur"}' the validation is triggered while typing?! I have no clue how to get this to work...

**Comment by shlomogoldstein** [comment]
I managed to get the behaviour by using this css. It will only display an invalid message if the input is not focused. The validation will fire anyways, but be invisible.

.ng-touched.ng-valid-validation:not(:focus) + i.icon.error {
  display: none;
}

.ng-touched.ng-invalid-validation:not(:focus) + i.icon.error {
  display: block;
}
