### ISSUE TITLE
Help with validate only just on submit

### ISSUE THREAD

**Issue by AlexEmashev** [ghiscoding/angular-validation#108]
Hello. I'm kind of lost a bit. May I ask for help? 

I've read wiki but didn't get the idea, how can I make form not validate on blur event. Instead validate whole form on **Submit** button. 

I'd like to show validation summary somewhere under the form or above it, without validation messages under inputs. 

Can someone help me with that? Here is a lame plunker for it http://plnkr.co/edit/ZdeuAQ7yLmKLO6jehNKz?p=preview

I've tried to use global options, but it seems I do it wrong.

**Comment by ghiscoding** [comment]
The onBlur event is always called, no matter what you do. But you might be able to do a bypass, at your own risk as I won't try it myself. So you could possibly use 1 of the [Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) property named `hideErrorUnderInputs` and make it to `True` but then you'll have no errors show under your inputs, so what you could possibly do is re-enable the errors under the inputs by changing it to `False` on a submit.

Something that could look like this:

```javascript
// inject the validationService inside your Controller
myApp.controller('Ctrl', function ($scope, validationService) {

  // start by create the ValidationService with a default of hiding the errors from showing
  var vs = new validationService({ hideErrorUnderInputs: true });


  vs.setGlobalOptions({ hideErrorUnderInputs: true });

 $scope.submit = function(){
   // when ready for submit, then re-enable the errors so they show up to the user
   vs.setGlobalOptions({ hideErrorUnderInputs: false });
    if(new validationService().checkFormValidity($scope.testForm)){
      $scope.status = "Submitted successfully!";
    } else {
      $scope.status = "Form not valid";
    }
  };
}); 
```

Give it a try, I don't see any other ways and I can't give much more help than that, so hopefully that's enough for you.

**Comment by AlexEmashev** [comment]
Wow, thank you so much. Your advice helped me.

Interesting thing is for some reason I don't have to use line:   `vs.setGlobalOptions({ hideErrorUnderInputs: true });` and it's still hides errors under inputs.

**Comment by ghiscoding** [comment]
Oh yeah hiding it through CSS is also valid and probably more efficient. Since you got it working, I will close the issue.
