### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by scottadamsmith** [ghiscoding/angular-validation#109]
Any chance of changing the package name to "angular-validation" as opposed to "angular-validation-ghiscoding"? I am not sure what the implications of changing this would be for others, but I know when I install this via NPM, I have to require or import "angular-validation-ghiscoding" to pull it into a module.

**Comment by ghiscoding** [comment]
As mentioned in your other post, I can't do it as there's already someone using that package name. There can't be any duplication of names so I went with adding my username at the end of it.
