### ISSUE TITLE
How to create validation on dynamic model

### ISSUE THREAD

**Issue by MaiklSemenov** [ghiscoding/angular-validation#114]
If we take the example "dynamic-input" and add some function to add item.
```
$scope.addData = function() { 
		$scope.data.unshift({
                        'name': "someName",
                        'title': 'someTitle',
                        'validate':"required"
                });
	}
```
Add create button 
`
<button type="button" class="btn" ng-click="addData()">Add item</button>
`
After that our model has new item, but validation dosn't work. How i can enable validation on new item?

**Comment by MaiklSemenov** [comment]
i'm sorry. It's ok. It was my problem

**Comment by ghiscoding** [comment]
I'm on vacations, so I'm a bit late for replies.

What does the html code look like? Do you have the `validation` attribute? Can you make a Plunker.

**Comment by ghiscoding** [comment]
If you can't provide a test case (with Plunker) for the error you're having, I will close this error in a few days. So please provide a test case.

**Comment by MaiklSemenov** [comment]
It's ok, it was my mistake.

**Comment by ghiscoding** [comment]
Great thanks for the answer
