### ISSUE TITLE
password pattern not working (a-z, A-Z, 0-9, [$@$!%*?&])

### ISSUE THREAD

**Issue by tatianass** [ghiscoding/angular-validation#116]
`var password = 'required|pattern=/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{6,10}/:alt=Minimum 6 characters at least 1 Uppercase Alphabet, 1 Lowercase Alphabet, 1 Number and 1 Special Character'`

I tested [here](https://regex101.com/r/vS8hC2/1):

**Comment by ghiscoding** [comment]
If you want help then please provide more details and a Plunker example. There is no mention of what is not working correctly.

**Comment by tatianass** [comment]
okay, I made it : [plunk](http://plnkr.co/edit/nivPCzdA0PGA2VScwHfI)

**Comment by ghiscoding** [comment]
You define your validation inside a string but you forgot to escape it. Since it's a string, you have to escape the `\` to be `\\` and to be more specific, in your example it is the `\d` which should be `\\d`.

```javascript
var password = "required|pattern=/^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[$@$!%*?&])[A-Za-z\\d$@$!%*?&]{6,10}/:alt=Minimum 6 characters at least 1 Uppercase Alphabet, 1 Lowercase Alphabet, 1 Number and 1 Special Character"
```

**Comment by tatianass** [comment]
It's working now, thanks!
