### ISSUE TITLE
Could I change the position for the message ?

### ISSUE THREAD

**Issue by maxhan247** [ghiscoding/angular-validation#118]
1. Could I place a valid/invalid message wherever I want ? I wish to change the position for validation message.
2. How can I show the success message, I already set the return value as { isValid: true, message: "success" }; but it doesn't show anything.

Thanks

**Comment by ghiscoding** [comment]
1. The default location of the error is below the input, though you can place it wherever you want using the `displayErrorTo` attribute. Take a look at the [Wiki - DisplayErrorTo / Bootstrap Input Groups Wrapping](https://github.com/ghiscoding/angular-validation/wiki/Bootstrap-Input-Groups-Wrapping)
2. The primary function of Angular-Validation is to remove error message when it's valid, while you want the opposite... However you can probably achieve what you want using [Wiki - Validation Callback](https://github.com/ghiscoding/angular-validation/wiki/Validation-Callback)

Please close the issue if that answers all your questions.

**Comment by maxhan247** [comment]
Great! it helps me a lot, Thank you very much!

**Comment by ghiscoding** [comment]
You're welcome, enjoy :)
