### ISSUE TITLE
Make in_list accept a dynamic value for the list

### ISSUE THREAD

**Issue by joshgarwood** [ghiscoding/angular-validation#119]
Hi there!

I'm loving this framework so far; it's awesome!  One thing that I am having trouble with though, is the "in_list" validator.  I'd love to be able to do something like this:

In controller
------------------
`vm.availableItems = api.getAvailableItems();`

In view
------------------
`validation="in_list:vm.availableItems"`

Would this be possible?

Thanks so much for your time!

**Comment by ghiscoding** [comment]
Angular-Validation supports transclusion, so maybe you could try `validation="in_list:{{vm.availableItems}}"`. I didn't try it though, but you might give it a try.

**Comment by ghiscoding** [comment]
I tried this over the weekend, it works as I said in my previous message though you have to follow a certain pattern. You have to make your list a CSV (comma separated) list as a String, then use it with transclusion in your view and it works. Make sure to remove any extra spaces from your CSV string, the `in_list` doesn't accept white spaces.

I took my Plunker demo to do these tests

in the Controller:
```javascript
myApp.controller('Ctrl', function ($scope) {
  var vm = this;
  vm.availableItems = "field1,field2,field3";
});
```

in the View (with transclusion)
```html
<input type="text" class="form-control" name="input21"  ng-model="input21" validation="in_list:{{vm.availableItems}}|required" />
```

If I enter the text "test" as a value it failed, then if I enter a correct value "field1" it passed.

To go with further tests, I also added a $timeout to simulate asynchronous call, as for example
in the Controller:
```javascript
myApp.controller('Ctrl', function ($scope, $timeout) {
  var vm = this;
  $timeout(function() {
      vm.availableItems = "field1,field2,field3";  
  }, 500);
});
```

The test with $timeout also worked. So I believe that it should be enough to prove that it works. 
With that being said, I'm closing the ticket unless you got something else worth reopening it.

If you like the Angular-Validation package, you can also click on the **Star** on top. 
Thanks for using it ;)

**Comment by joshgarwood** [comment]
Thanks so much for the super quick response!!  So you're totally right in that the value gets transcluded, I just needed to call ".join()" to get a comma delimited list as opposed to an array or strings.
