### ISSUE TITLE
Directive for prevalidating form

### ISSUE THREAD

**Issue by joshgarwood** [ghiscoding/angular-validation#120]
Hello again!

So sorry to be a bother, but I have another question/suggestion... I noticed that you have a global option for setting preValidation to true, but I'm wondering if it would be possible to add this option as a directive on a form so we can selectively choose when to preValidate.

For instance, on any of my forms where a _new record_ is being created, I don't want to prevalidate.  BUT, for forms that are _editing_ existing data, I do want to prevalidate.  Normally this wouldn't be a problem, but we're developing against a system that has bad data and want to validate when an edit form loads so it's clear which fields are bad.

Is this possible?

**Comment by ghiscoding** [comment]
I think you can do it easily just by calling directly the `checkFormValidity()` from the `ValidationService`. When your form loads and you know that it's an Edit Form, just call the check and errors will display right away on screen. Basically do a `checkFormValidity()` when you load the Edit form and redo another `checkFormValidity()` when you save it.

```javascript
// inject the ValidationService inside your Controller
myApp.controller('Ctrl', function ($scope, ValidationService) {
  var vm = this;
  var vs = new ValidationService({ controllerAs: vm });

  // find out how to know it's editing then call the checkFormValidity right away
  if(formType == 'edit') {
    vs.checkFormValidity(vm.form1); // the check form will instantly display all errors on screen
  }
  
  // functions declaration

  vm.submit = function () {
     if(vs.checkFormValidity(vm.form1)) {
         // proceed with submit
     }
});
```

I am not intending to add more functionalities to this Directive/Service, it's already including a lot already. At this point, I just want to maintain it, if need be.

Please **close** the issue if that make sense with your request

**Comment by joshgarwood** [comment]
I totally understand; you've done an amazing job with this framework!  But I just tried your code above and got this error in the console:

Angular: {"e":"checkFormValidity() requires a valid Angular Form or $scope/vm object passed as argument to work properly, for example:: fn($scope) OR fn($scope.form1) OR fn(vm) OR fn(vm.form1)","logData":"<span ui-view=\"{{tab.route}}\" class=\"ng-scope\" data-ng-animate=\"1\">"}

This is what I have in my controller:

```
var vs = new ValidationService({controllerAs: vm});
        
// find out how to know it's editing then call the checkFormValidity right away                
vs.checkFormValidity(vm.inputForm); // the check form will instantly display all errors on screen
```

This is my view:
```
 <form name="inputForm" class="form-horizontal"  ng-submit="vm.updateTripType()" novalidate>
   <div class="form-group">
            <label class="col-sm-3 control-label">One Way Profile</label>

            <div class="col-sm-7">
                <select class="form-control" name="OneWayTripNotificationProfileId" 
                        ng-options="item.sdProfileId as item.name for item in vm.tripProfiles"                        
                        ng-model="vm.fields.OneWayNotificationProfileId"
                        validation="required|in_list:{{ vm.validation.acceptableTripProfiles }}:alt=Please select an item from the list">
                </select>
            </div>
        </div>
</form>
```

I double checked and vm.inputForm is a valid angular form object.  Am I missing something?

**Comment by ghiscoding** [comment]
The name of your form is `inputForm` which doesn't match `vm.inputForm`

You should probably change this `<form name="inputForm" ... >` to this `<form name="vm.inputForm" ... >`

**Comment by joshgarwood** [comment]
Hmmm, i tried that and got the same thing.  I've attached an image that shows my controller on the left, my view on the right, and the error in the console in the bottom left.  I'm not sure if it makes a difference, but this is a nested view using ui-router.  I wouldn't think it would matter, but I thought I would mention it just in case.

Thanks again!
![error](https://cloud.githubusercontent.com/assets/1417324/15841142/e53191b8-2c1c-11e6-924f-d096d6142a68.png)

**Comment by joshgarwood** [comment]
Ah-ha!!  It woudl seem as though there is a race condition here.  I had to wrap the checkFormValidity in a $timeout in order to allow the DOM to render before checking the validity.  I also created a directive for this if anyone else is interested:

Assuming your form is named: "inputForm":

```
(function () {
    'use strict';

    angular
        .module('app.directives')
        .directive('prevalidateForm', prevalidateForm);

    function prevalidateForm(ValidationService, $timeout) {
        return {
            restrict: 'A',
            link: function (scope, element, attrs) {
                
                scope.preValidateTimeout && $timeout.cancel(scope.preValidateTimeout);
                
                // We delay the the execution of the validation to allow the DOM to finish
                //  rendering.  This allows the checkFormValidity function to execute properly. 
                scope.preValidateTimeout = $timeout(function() {
                    var vs = new ValidationService();                
                    vs.checkFormValidity(scope.inputForm);
                }, 50);                  
            }
        };
    }
})();
```

**Comment by ghiscoding** [comment]
Glad you found a solution to your problem, timeout and out of sync problems are indeed big factors. 
If I understand correctly, we can now close this issue?
