### ISSUE TITLE
Alternate Text on Validators cannot contain ':' char

### ISSUE THREAD

**Issue by pszerszen** [ghiscoding/angular-validation#121]
When alternative text on a validator contains ':' character, the displayed message is being cut from this very position.
Example:
Actual validation message: "Must be a valid datetime format (rrrr-MM-dd HH:mm)."
Displayed message: "mm)."

**Comment by ghiscoding** [comment]
Can you create a quick plunker if you want me to debug this. You can use the [Live Demo on Plunker](http://plnkr.co/jADq7H)

**Comment by ghiscoding** [comment]
Thanks for your patience, this issue is now fixed in latest [version 1.5.2](https://github.com/ghiscoding/angular-validation/releases/tag/v1.5.2)

If you like the package, you can also click on the :star: on top. Thank you
