### ISSUE TITLE
Custom Regular Expression Pattern as a variable

### ISSUE THREAD

**Issue by maxhan247** [ghiscoding/angular-validation#123]
Hi there!

Is small question about custom regular expression Pattern

In my html:
```
<input ng-model="vm.user.password" name="password" type="password"
validation="required:alt=empty|pattern=vm.pattern:alt=weak password"
validation-error-to="passwordMessage">......

```

In my ctrl:
...
`vm.pattern = "/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[_\W]).+$/";`

I wish to change the pattern as a string variable in controller, but seems it not work. It is something I miss ?

Thanks

**Comment by ghiscoding** [comment]
Regular expression don't need to be declared as string, you can omit the double quotes without any problems. However if you really want to use the double quotes then you need to escape the string, especially the `\` should be `\\`

**Comment by maxhan247** [comment]
Thanks for great and really quick response !

**Comment by maxhan247** [comment]
Hello I create a plnkr: http://embed.plnkr.co/tFzDxmgdX66NO7vaD9H3/

I omit the double quotes, but seems it is still not work.

**Comment by maxhan247** [comment]
Thank you very much for reply, the reason why I pass it as a string is the vm.reg is not static, it will change based on different password policy (load from file). I will double check your example. Thank you very much.
