### ISSUE TITLE
After error message, all below components are displaced

### ISSUE THREAD

**Issue by gfpalacios** [ghiscoding/angular-validation#127]
The validation adds a span tag under the validated input field but I cause that all below component are displaced down. How can I fixed that? I guess I could use a div instead of span but I am not sure. 

I saw the code in validation-common.js and you mentioned that the error message could be shown as div. So, is it possible?

`
 /** Validate function, from the input value it will go through all validators (separated by pipe)
     *  that were passed to the input element and will validate it. If field is invalid it will update
     *  the error text of the span/div element dedicated for that error display.
     * @param string value: value of the input field
     * @param bool showError: do we want to show the error or hide it (false is useful for adding error to $validationSummary without displaying it on screen)
     * @return bool isFieldValid
     */
    function validate(strValue, showError) {
`

Thanks!

**Comment by ghiscoding** [comment]
Simply use [Wiki - DisplayErrorTo](https://github.com/ghiscoding/angular-validation/wiki/Bootstrap-Input-Groups-Wrapping) which was made for this

**Comment by gfpalacios** [comment]
Sound good! Thank you for your quick response!
