### ISSUE TITLE
angular-validation is not found by browserify

### ISSUE THREAD

**Issue by jsmarsch** [ghiscoding/angular-validation#128]
If you use browserify to concatenate your js files and to make them work as modules, the angular-validation js file is never picked up.

As a result, angular's DI err's with this message: 

> Failed to instantiate module ghiscoding.validation due to:
> Error: [$injector:nomod] Module 'ghiscoding.validation' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
> 
(this is because angular-validation.min.js is never added to the concatenated .js file)

The problem is in the package.json file in the angular-validation node_modules folder.  "Main" should reference "dist/angular-validation.min.js", instead of app.js (I did find the app.js file concatenated in my output)

**Comment by ghiscoding** [comment]
Could you please post a fix, I would be happy to accept your PR

**Comment by jsmarsch** [comment]
You bet!  It will be a few days.  We are still getting some other aspects of our app switched over to CommonJS modules with Browserify, so I'll post the fix when everything is working.  There are also some issues with angular-translate.  

Right now, I have angular-validation partially working -- I know that is is validating, because checking $invalid on my form object works (is true or false consistently with the validation rules).  However, the validation messages are not appearing on-screen, and the input boxes are not changing color when they are invalid.  I'm hoping that when I get angular-translate squared away, the messages will start working.

**Comment by ghiscoding** [comment]
Sounds good, I'll wait for the PR. 

You mention that you are missing `angular-translate` and indeed it is a requirement which most probably explain the error messages not showing. Also make sure to have the proper CSS styling in your project to get the inputs to change color. You can read the [Wiki - HOW TO](https://github.com/ghiscoding/angular-validation/wiki/HOWTO---Step-by-Step), there's a lot of good information in there.

If you haven't already, click on the :star: when you get it all going. Cheers ;)

**Comment by ghiscoding** [comment]
Hello, I was just wondering if you ever came up with an answer to your open issue?

**Comment by Gusi** [comment]
https://github.com/ghiscoding/angular-validation/pull/136

**Comment by ghiscoding** [comment]
Thanks @Gusi for the fix, I forgot to bump the version at first so that's why you might see 2 releases. Here's the latest released [version 1.5.9](https://github.com/ghiscoding/angular-validation/releases/tag/v1.5.9)
