### ISSUE TITLE
angular-validation break enter to submit the form

### ISSUE THREAD

**Issue by sonphnt** [ghiscoding/angular-validation#129]
Hi,

I have Username/Password textbox in login form and applied angular-validation on each. When I hit enter  (there is a button login submit) to login but I had to enter twice or 3 times, remove validation then enter work properly.

Is it a bug?

Thanks

**Comment by ghiscoding** [comment]
Can you make a plunker of this? You're maybe missing something somewhere.

**Comment by sonphnt** [comment]
Hi ghiscoding

Here is a simple I just made
https://plnkr.co/edit/cb0Y2RKZcP8f1IqTSO8l?p=preview

I am using Google Chrome browser. Press enter 2-3 times to login confirmed but if you remove validation="required" of input then it works normally.

Thanks

**Comment by ghiscoding** [comment]
Hello, I'm not sure to fully understand your issue but I see some errors in your implementation so perhaps that might be it.

You should have an `ngClick` or `ngDisabled` on your button, pick whichever you prefer but you should definitely have one of them
```html
<!-- with ngClick -->
<button class="btn btn-primary btn-block" type="submit" ng-click="signIn()">Login</button>

<!-- or with ngDisabled -->
<button class="btn btn-primary btn-block" type="submit" ng-disabled="loginForm.$invalid">Login</button>
```

Then inside your ngApp, you are missing the dependency and configuration of `$translateProvider`, without it, it basically won't work at all.
```javascript
myApp.config(['$translateProvider', function ($translateProvider) {
	  $translateProvider.useStaticFilesLoader({
	    prefix: 'https://rawgit.com/ghiscoding/angular-validation/master/locales/validation/',
	    suffix: '.json'
		});
  
  	// load English ('en') table on startup
		$translateProvider.preferredLanguage('en').fallbackLanguage('en');
		$translateProvider.useSanitizeValueStrategy('escapeParameters');
	}]);
```

Then if you use the `ngClick`, as I wrote earlier, you should then use the `ValidationService` to kick in the validation (by default it doesn't show any validation errors and that's normal, you don't want to annoy your user at first). Using the `ValidationService`, your `signIn()` function should be:
```javascript
$scope.signIn = function () {
    if(vs.checkFormValidity($scope)) {
      $scope.message = 'logged in';
    }
  };
```

You could pre-validate the form, I rarely recommend that but it's an option. See it here [Wiki - PreValidate Form](https://github.com/ghiscoding/angular-validation/wiki/PreValidate-Form-(on-page-load)). 

It might also be helpful to read the full [Wiki - HOWTO Step by Step](https://github.com/ghiscoding/angular-validation/wiki/HOWTO---Step-by-Step)

Finally if I take your [plunker](https://plnkr.co/edit/cb0Y2RKZcP8f1IqTSO8l?p=preview) and I modify it (I'm only showing the `app.js`, you should still modify the `index.html` with the `ngClick` or `ngDisabled` as I wrote earlier). So here's the full code
```javascript
'use strict';

var myApp = angular.module('myApp', ['ngSanitize', 'ghiscoding.validation', 'pascalprecht.translate']);

// include validation languages
// if you want full localization add it in the suffix
// For example on Canadian French/English, we could replace the code by `suffix: '-CA.json'`
myApp.config(['$translateProvider', function ($translateProvider) {
	  $translateProvider.useStaticFilesLoader({
	    prefix: 'https://rawgit.com/ghiscoding/angular-validation/master/locales/validation/',
	    suffix: '.json'
		});
  
  	// load English ('en') table on startup
		$translateProvider.preferredLanguage('en').fallbackLanguage('en');
		$translateProvider.useSanitizeValueStrategy('escapeParameters');
	}]);


myApp.controller('Ctrl', ['$scope', '$translate', 'ValidationService', function ($scope, $translate, ValidationService) {
  // set the global options BEFORE any function declarations, we will prevalidate current form
  var vs = new ValidationService();
  
  $scope.signIn = function () {
    if(vs.checkFormValidity($scope)) {
      $scope.message = 'logged in';
    }
  };
}]);
```

**Comment by sonphnt** [comment]
Hi ghiscoding,

Basically We can add ng-click="signIn()" on button element or we use ng-submit on form. But anyway, I have changed the way using ng-submit on form to ng-click on button as you described. But it is still a problem. You can reproduce it following:

When app loaded, you type Username, type Password, press Enter. The method signIn() in scope was not triggered instantly, and you will not see the message "logged in" below the button. Press Enter one more time or sometimes two more, now signIn() is triggered, and you will see the message below button. It seems like working with Firefox but failed with Chrome.

But Instead of pressing Enter to login. If you type Username, type Password and use mouse to click on button. signIn() is also triggered instantly.

I have not applied ValidationService yet in Controller. The $scope.signIn() need to be triggered correctly at the first Enter before we can go further applying checkFormValidity() inside it.

Thanks

**Comment by ghiscoding** [comment]
Have you tried the code that I gave you? If I run the app with the code I provided, it works instantly also with Enter (after typing Username, Password then press Enter while being on the Password input). I did not change anything else from the code I provided and it works. So please give it a try.

**Comment by sonphnt** [comment]
Hi ghiscoding,

Now the code has worked properly even I use ng-submit or ng-click. It is weird. Perhaps, my browser had a problem.

Thank for your help.

**Comment by ghiscoding** [comment]
Ok good to know, it might be release change too. I pushed some small changes lately. 

Anyhow, thanks for closing the issue and enjoy the package :)
