### ISSUE TITLE
Show validation errors when the user clicks the 'Submit' button

### ISSUE THREAD

**Issue by juanchavezlive** [ghiscoding/angular-validation#13]
In order to made more easy for the user the identification of the validation errors, it would be great to show all the validations errors when the users clicks the 'Submit' button, instead of disable the submit button until the user correct all the validation errors.

**Comment by juanchavezlive** [comment]
Example:

![1](https://cloud.githubusercontent.com/assets/5005394/6808602/aa344db0-d233-11e4-9e7a-3fc35e6eca55.png)

**Comment by ghiscoding** [comment]
Hello, I'm not sure how to do that one yet but in the mean time you can use the Validation Summary that I added last weekend, and connect it to your submit button. Make an `ngClick` function, on errors prevent the submitting and display errors summary. 

```javascript
$scope.submit = function (event) {
	if($scope.form1.$invalid) {
		$scope.displayValidationSummary = true;
		event.preventDefault();
	}	
}
```
