### ISSUE TITLE
Age (date) validation

### ISSUE THREAD

**Issue by brunowego** [ghiscoding/angular-validation#131]
What think about a validation for age? It's appropriated?

```html
<input ... validation="age:18|required" />
```

---

Related #130

**Comment by ghiscoding** [comment]
just use the `min_num:18` with the `alt` property [Wiki - Alternate Text](https://github.com/ghiscoding/angular-validation/wiki/Alternate-Text-on-Validators)

```html
validation="min_num:18:alt=Must be legal of age"
```

**Comment by brunowego** [comment]
Really? I need read again the docs! Sorry for my mistake.

**Comment by brunowego** [comment]
@ghiscoding I mean for birthdate validation, not for a integer number.

**Comment by ghiscoding** [comment]
Do you mean date calculation? That's getting too customized, you should look into building your own custom javascript function for that... [Wiki - Custom Validation](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions)

**Comment by brunowego** [comment]
Yep, is a good alternative. Thanks!
