### ISSUE TITLE
Angular-ui-select support?

### ISSUE THREAD

**Issue by sonphnt** [ghiscoding/angular-validation#132]
Hi,

Does angular-validation support for angular-ui-select ?
It does not seems to work well.

Thanks

**Comment by ghiscoding** [comment]
This should help you [Wiki - 3rd Party Addons](https://github.com/ghiscoding/angular-validation/wiki/3rd-Party-Addons)

**Comment by sonphnt** [comment]
[plunk.zip](https://github.com/ghiscoding/angular-validation/files/498617/plunk.zip)

Hi ghiscoding,

I have made a plunk but I was not able to save it. Can you please see my attched?
The textbox is validated well but ui-select does not. I dont use the way of 'vm' . I put directly to $scope. I am not sure if that is a problem

Your example is working fine but you use vm as controller.

Thanks

**Comment by sonphnt** [comment]
Hi ghiscoding,

Thank for your information. I have made it work with this code:
`(function () {
    'use strict';
    angular.module("skype.index", [])
	.controller("SkypeIndexCtrl", ["$scope", "$state", "ValidationService", SkypeIndexCtrl]);

    function SkypeIndexCtrl($scope, $state, ValidationService) {
        var myValidation = new ValidationService();

        $scope.select1data = [
          { Id: 1, Name: "Joe" },
          { Id: 2, Name: "John" },
          { Id: 3, Name: "Jane" }
        ];

        $scope.submit = function () {
            if (myValidation.checkFormValidity($scope)) {
                alert('valid');
            }
        };
    }
})();`

`<form name="test">
                        <div class="form-group">
                            
                            <ui-select ng-model="mySelection" search-enabled="false" name="licenseoptions" validation="required" validation-array-objprop="Name">
                                <ui-select-match placeholder="Select...">{{mySelection.Name}}</ui-select-match>
                                <ui-select-choices repeat="item in select1data">
                                    <span ng-bind="item.Name"></span>
                                </ui-select-choices>
                            </ui-select>
                        </div>

                        <div class="form-group">
                            <label>
                                Textbox
                            </label>
                            <input type="text" name="Message" class="form-control" ng-model="Message" validation="required">
                        </div>

                        <button class="btn btn-primary" type="submit" ng-click="submit();">Save changes</button>
                    </form>`

No need to give a form (vm.test) in checkFormValidity() and it worked.

**Comment by ghiscoding** [comment]
Glad you got it working, so I assume that I can close this issue :)
