### ISSUE TITLE
Dutch and Romanian Translation

### ISSUE THREAD

**Issue by jdriesen** [ghiscoding/angular-validation#134]
Hi Ghislain,

As promised a couple of days ago, I hereby send you the DUTCH and ROMANIAN translation.

I'm certainly NOT a Github expert (don't know in detail how PR's are working) , that's why I'm sending the translated files as attachments to this issue. (had to upload them as a zip ...)

Feel free to make them available in your project.
Thanks again for sharing this wonderful piece of software ! (and YEP, I 'starred' it :) )

Kind regards,
Johnny (Belgium)
[nl_ro.zip](https://github.com/ghiscoding/angular-validation/files/505643/nl_ro.zip)

**Comment by ghiscoding** [comment]
All done, thanks a lot for providing these new locales. I now have 10 supported locales, that's awesome :)
