### ISSUE TITLE
Validation message not showing on ng-repeater after back navigation.

### ISSUE THREAD

**Issue by caseyoconnor** [ghiscoding/angular-validation#137]
First, thank you for writing this library.

We have an ng-repeater with (n) columns wide and a few rows. Each column has an input element that can be updated, thus it needs validation. When we navigate to a new route and then either click the browsers back button and or ng-click back to the route the validation occurs but the div below does not show.

<div class="validation validation-buildingAmount0 text-danger">Field is required.</div>

We have tried to use the validation-error-to directive and explicitly added a div in hopes that this would be a work around but it was not a successful attempt.

Below I have made a plunker that begins on the "Home" view then navigates to "People" with a repeater and then on to an "Away" route. If you run the plunker and you click to the Away route and then go back you will notice when you clear out the input field that the validation message does not show. However the validation message will show before you $state.go to another route.

https://plnkr.co/edit/AvazGJNmbjR1x2T4RMfS

While making the plunker and simply using  window.location.href = 'http://www.google.com'; I was able to navigate back and I believe the validation message fired.

This leads me to wonder if the combination of angular-ui-router with the ghiscoding-validation is the issue?

**Comment by ghiscoding** [comment]
Hmm I have noticed this in the past, but never got time to debug it. It might be a timing issue, there's so many timing issue in Angular that's it's annoying sometime to debug. Also, I can see that the ValidationSummary doesn't get filled in correctly either (it works on first load but not after leaving and coming back). You can see the summary by adding this

```javascript
<div class="alert alert-danger alert-dismissable">
    <ul>
        <li ng-repeat="item in validationForm.$validationSummary">{{item.field }}: {{item.message}}</li>
    </ul>
</div>
```

I seriously don't know when I'll have time to debug this. I'm trying to work on some other things in my free time. However, that seem to be where to start

**Comment by ghiscoding** [comment]
Hello and sorry for the delay, I am planning on passing more time in resolving some of these issues during my upcoming Christmas holiday. I was looking at some of my Global Options available and just remember that I have an option called `resetGlobalOptionsOnRouteChange` [Wiki - Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) that is specifically used with the regular `Angular Route`, that is used in the [validation-common.js](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-common.js) file at line 24. 

Would you be able to use the unminified version of `Angular-Validation` and change that line 24 with the `UI Router` watch and see if that makes any difference? Specifically, change the line 24 from `$rootScope.$on("$routeChangeStart"` to `$rootScope.$on("$stateChangeStart"`

I will probably need another Global Option asking which Router has the user setup in his project and make the regular `Angular Route` as default.

**Comment by ghiscoding** [comment]
Actually this was bothering me too much, so I made a quick change in my code (I added a second watch for  `UI Router`), ran all my Protractor tests and pushed a quick [version 1.5.10](https://github.com/ghiscoding/angular-validation/releases/tag/v1.5.10) and that seem to have fixed the issue in the Plunker you provided. 

I will close this issue for now since I think that it's fixed (if not, I can re-open it).
Please confirm, thanks
