### ISSUE TITLE
custom do not work

### ISSUE THREAD

**Issue by acordovar** [ghiscoding/angular-validation#138]
Hi,

I need to validate with a condition. I have defined the following function in my Controller:

this.validarPasswordForm = function () {
            var isValid = true;
            if (t.proceso == "autenticar") {
                if (!t.userDTO.Password)
                    return { isValid: false, message: "El Password es un dato requerido." };
            }
            return isValid;
        }

My controller starts like this:

function autenticacionController(autenticacionService, $scope, ValidationService) {
        var t = this;
        var vs = new ValidationService({ controllerAs: t });
...
}

My control in HTML:

<div class="form-group">
                            <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Contraseña</label>
                            <input type="password" class="form-control" id="txtContrasenaP0A" name="txtContrasenaP0A" placeholder="Ingrese Contraseña" ng-model="ctrl.userDTO.Password" validation="custom:ctrl.validarPasswordForm()">
                        </div>

I've tried debugging and it never comes into my function.

Thanks in advance!

**Comment by ghiscoding** [comment]
It most probably doesn't work because you are not calling your `Controller As` the same name. You're doing a `controllerAs: t` however you are calling it as `custom:ctrl.validarPasswordForm()`. Try to make it the same name and see if that helps or not. 

You also have to know that `Angular-Validation` permits you to pass the function name as a string `custom:ctrl.validarPasswordForm()` but doing so has some downside, like for example name have to match an be found in the Controller.

**Comment by acordovar** [comment]
Thank You!
I will follow your advice.

Regards!
________________________________
De: Ghislain B. <notifications@github.com>
Enviado: lunes, 14 de noviembre de 2016 08:45:14 p.m.
Para: ghiscoding/angular-validation
Cc: acordovar; Author
Asunto: Re: [ghiscoding/angular-validation] custom do not work (#138)


It most probably doesn't work because you are not calling your Controller As the same name. You're doing a controllerAs: t however you are calling it as custom:ctrl.validarPasswordForm(). Try to make it the same name and see if that helps or not.

You also have to know that Angular-Validation permits you to pass the function name as a string custom:ctrl.validarPasswordForm() but doing so has some downside, like for example name have to match an be found in the Controller.

-

**Comment by ghiscoding** [comment]
If that work, can we close this issue? 

Thanks

**Comment by ghiscoding** [comment]
I will close it since I didn't hear anything back.
