### ISSUE TITLE
Add Spanish & Portuguese translations to angular-validation

### ISSUE THREAD

**Issue by juanchavezlive** [ghiscoding/angular-validation#14]
Add Spanish (es-ES) translations to angular-validation.
Add Portuguese (pt-BR) translations to angular-validation.

**Comment by juanchavezlive** [comment]
The Spanish translations will be add by @juanchavezlive (Native Spanish speaker)
The Portuguese translations will be add by @mariomeyrelles (Native Portuguese speaker)

@mariomeyrelles thanks a lot for your support.

**Comment by ghiscoding** [comment]
That will be great to have, please make a pull request using same locale json files.
Thank you from both of you

**Comment by juanchavezlive** [comment]
Pull request #18 created for the spanish translations
https://github.com/ghiscoding/angular-validation/pull/18

**Comment by ghiscoding** [comment]
Thanks for the Spanish version, I will leave this discussion open as I believe the Portuguese will come later... Thanks again

**Comment by ghiscoding** [comment]
Hello, I am just wondering if your friend forgot about us? It would be nice to have the translation and close this open subject.. have a nice day :)
