### ISSUE TITLE
Custom directive validation

### ISSUE THREAD

**Issue by LennyLip** [ghiscoding/angular-validation#140]
I have several custom directive , like a 

```
 <multi-select-tree name="category" ng-model="category.selectedCategory[0]" ng-required="true"></multi-select-tree>
```

so, early, when is set ng-required="true" , angular-validation (don't remeber version) is work ok and 

`validationService().checkFormValidity($scope.formScope.Form);
`

return False ,  when category.selectedCategory[0] is undefined. (
Now, with  @version: 1.4.4 it does not work. checkFormValidity return true, when  category.selectedCategory[0] is undefined.  (I think it just not test that from.$valid now? I have form.$valid is false, but checkFormValidity return true) 

So, i've been tried to set validation="required" into directive (all of custom) and now i get while load script:

```
angular.js:13424 TypeError: Cannot read property 'toUpperCase' of undefined
    at C.g [as validate] (angular-validation.min.js:10)
    at Array.d (angular-validation.min.js:9)
    at angular.js:26733
    at m.$digest (angular.js:16860)
    at m.$apply (angular.js:17133)
    at g (angular.js:11454)
    at x (angular.js:11652)
```

**Comment by ghiscoding** [comment]
Hello, I'm sorry but I don't understand your problem and don't know how to help you. However I suggest you to use the unminified version of `Angular-Validation` and try to find where it fails. I'm giving much less time to this library as I work on some other things, however I accept PR.

**Comment by LennyLip** [comment]
@ghiscoding 

Ok, simple question
should validationService().checkFormValidity($scope.Form) return True while $scope.Form.$valid is false?

**Comment by ghiscoding** [comment]
Sorry, I thought I had answered to your question but it seems that I forgot to click on send. Anyhow, the answer is that `Angular-Validation` doesn't use the validation of the form itself, instead it uses the `$validationSummary` and if that is empty will return `true`. There's an unknown problem with using the form name, you could however use only `$scope` and that should have better results like so `validationService().checkFormValidity($scope)`.

**Comment by LennyLip** [comment]
many thanks! 
the first issue has been resolved.
Second issue is validation of custom directive... I will try  unminified version.

**Comment by ghiscoding** [comment]
I haven't put much time on this library recently but I would like to close all open issues during my upcoming holiday if possible. If you're able to create a Plunker and describe the process that might help.

**Comment by ghiscoding** [comment]
I have put in a fix for a long standing problem I've seen with passing `formName` to `checkFormValidity()` and so, `checkFormValidity($scope.formName)` should work as expected. 

Please update to your project to latest [version 1.5.11](https://github.com/ghiscoding/angular-validation/releases/tag/v1.5.11).

**Comment by ghiscoding** [comment]
A small issue was created by prior version, please update to [version 1.5.12](https://github.com/ghiscoding/angular-validation/releases/tag/v1.5.12) to be on the safe side. 

Could you also close the issue, if this fixes it. Thanks

**Comment by ghiscoding** [comment]
I would like to close all issues by year end, I didn't hear any news from your side and so, I'll consider this issue fixed unless you come back and say it's not (we can also reopen the issue later if it comes back).

**Comment by LennyLip** [comment]
version 1.5.12

template:
```
<form novalidate name="descForm" ng-init="setFormScope(this)">
 <multi-select-tree name="category" ng-model="category.selectedCategory" ng-required="true"></multi-select-tree>
</form>
```

controller:
```
$scope.setFormScope= function(scope){
       $scope.formScope = scope;
}
```
(I have a complex template with several scopes.)

ng click console log:
```
"category.selectedCategory":undefined
"new ValidationService().checkFormValidity($scope.formScope.descForm)": true
"$scope.formScope.descForm.$valid": false
```

**Comment by ghiscoding** [comment]
If you are using different scopes, you need to tell `Angular-Validation` about it. Refer to the [Wiki - IsolatedScope](https://github.com/ghiscoding/angular-validation/wiki/Isolated-Scope) and set `isolatedScope` in your global options
