### ISSUE TITLE
Unable to work with Modal form

### ISSUE THREAD

**Issue by SigmaSoftSol** [ghiscoding/angular-validation#145]
Hello Team,
   I have implemented the validation Service in one of the Modal Form.  The validationService().CheckFormValidity is thorwing error "checkFormValidity() requires a valid Angular Form or $scope/vm object passed as argument to work properly,".

I have provided the code like this in the submit button.

`if (myValidation.checkFormValidity($scope.addDevelopmentInformation)) {
            alert('All good, proceed with submit...');
            $scope.newDevelopment.CreatedBy = $rootScope.LoggedInUserInformation.UserId;
            developmentInformationService.saveDevelopmentInformation($scope.newDevelopment).then(function (data) { $uibModalInstance.close('Development Data has been Saved'); });
        } else {
            alert('Some Errors are there');
        }`

Could you please help me to resolve the issue.

Thanks & Regards,
Seshu Kumar.

**Comment by ghiscoding** [comment]
You need to use the [Wiki - isolatedScope](https://github.com/ghiscoding/angular-validation/wiki/Isolated-Scope) for that to work
