### ISSUE TITLE
validation custom directive

### ISSUE THREAD

**Issue by shomid** [ghiscoding/angular-validation#147]
[http://plnkr.co/edit/Sr7NZIcjf13p9EEZe3PL?p=preview](http://plnkr.co/edit/Sr7NZIcjf13p9EEZe3PL?p=preview
)

when user focus in custom directive(first element in sample) then blur without value, validation not show any error message.
but user focus in input tag(second element in sample) then unfocus without value,validation show error message .

why validation not show error message for my custom directive ?

**Comment by ghiscoding** [comment]
Did you copy the [CSS Styling](https://github.com/ghiscoding/angular-validation/blob/master/style.css) from the examples I made? Also which browser and AngularJS function are you using?

**Comment by shomid** [comment]
I added css styling to plnker example but not correct .
I use of chrome 54 .

Please see plnkr link [http://plnkr.co/edit/Sr7NZIcjf13p9EEZe3PL?p=preview](http://plnkr.co/edit/Sr7NZIcjf13p9EEZe3PL?p=preview)

validation not work for custom directive .

**Comment by ghiscoding** [comment]
Your custom element `<my-input/>` (let's call it the Parent) is creating a regular input (the Child) but you didn't pass the `validation` attributes to the Child input. You need to pass the `validation` attribute to the `<input/>`  that is inside the Directive.

**Comment by ghiscoding** [comment]
You can take a look at this [custom input template example](https://github.com/ghiscoding/angular-validation/tree/master/more-examples/dynamic-input) which was created by another user. It is similar to your problem.

**Comment by ghiscoding** [comment]
This is partially working, don't have more time to spend [http://plnkr.co/edit/ZWgTxOm4WYNYyHQhG8H0](http://plnkr.co/edit/ZWgTxOm4WYNYyHQhG8H0)

**Comment by shomid** [comment]
thank you
