### ISSUE TITLE
validation rule "different" disables rule "required"

### ISSUE THREAD

**Issue by MarekRychlik** [ghiscoding/angular-validation#151]
It seems that when validation rules "different" and "required" are used together, the "required" rule is not enforced.

**Comment by ghiscoding** [comment]
If you had time to troubleshoot the issue that would be great because I don't have much time to spend on this lately.

**Comment by ghiscoding** [comment]
I will be going in vacations for a few weeks, which is why it would be nice if you had time to troubleshoot, else that will have to wait. Thanks

**Comment by ghiscoding** [comment]
Made a fix and published a new [release 1.5.21](https://github.com/ghiscoding/angular-validation/releases/tag/v1.5.21) on [NPM](https://www.npmjs.com/package/angular-validation-ghiscoding).

I saw the behavior in my [Plunker demo](http://plnkr.co/jADq7H) and it seems to be fixed now. Let me know if it's still problematic. Thanks for feedback
