### ISSUE TITLE
Require for radio buttons?

### ISSUE THREAD

**Issue by jsmarsch** [ghiscoding/angular-validation#154]
How would I add a "required" validation on a group of radio buttons? (so that the user must make a selection?)

**Comment by ghiscoding** [comment]
Hello, sorry about the delay I was away in vacations for the past few weeks. I haven't used it with radio buttons yet, so I can't really say. What have you tried so far? Might need a plunker

**Comment by ghiscoding** [comment]
I tried it and it works good with radio, I don't see any issue here so I'll close this issue. I will eventually update the sample to have a `radio` example.

Here's a quick sample that works

```html
<div class="form-group">
    <label for="input23">Choose a color</label>
    Red <input type="radio" id="radioColor_red" ng-model="radioColor" value="red" validation="required" validation-error-to=".validation-input23">
    Blue <input type="radio" id="radioColor_blue" ng-model="radioColor" value="blue" validation="required" validation-error-to=".validation-input23">
    Green <input type="radio" id="radioColor_green" ng-model="radioColor" value="green" validation="required" validation-error-to=".validation-input23">
</div>
<span class="validation-input23 validation text-danger"></span>
```

**Comment by ambasador** [comment]
hi i've different issue one of the radio button is required only, second is not required. it's working only when i check for the first time but when i check radio with value no validation is not working  

`<div class="form-group">
    <label for="input23">Agree</label>
    Yes <input type="radio" id="radioColor_red" ng-model="radioColor" value="yes" validation="required" validation-error-to=".validation-input23">
    No <input type="radio" id="radioColor_blue" ng-model="radioColor" value="no" >
</div>
<span class="validation-input23 validation text-danger"></span>`
