### ISSUE TITLE
Error validating a form

### ISSUE THREAD

**Issue by YamilBracho** [ghiscoding/angular-validation#155]
Hi,
I would like to validate all my fiedls in my submit button, so I have my form :+1: 
<form method="POST" action="${url}" modelAttribute="inscripcion" id="defuncionForm" name="defuncionForm" novalidate>

And in my submit button I got :+1: 
		$scope.sendForm = function() {
			if (vs.checkFormValidity($scope.defuncionForm)) {
				helper.save();
			}
And in console this error is shown :
angular.js:14324 checkFormValidity() requires a valid Angular Form or $scope/vm object passed as argument to work properly, for example:: fn($scope) OR fn($scope.form1) OR fn(vm) OR fn(vm.form1)

It seems to me that defuncionForm is not recognized as avalid HTML form ??

TIA,
Yamil

**Comment by ghiscoding** [comment]
Do you have a form name in your html? Can you include the form declaration in the issue, just want to see the name. 

I had issues with the `checkFormValidity()` function in the past (when passing a form name), I thought that I fixed them all but who knows, there might be still some issues with it. Another thing you can do which works better, if you only 1 form in the page, is to pass just the `$scope`, like this `vs.checkFormValidity($scope)`

**Comment by YamilBracho** [comment]
Hi, 
Yes, i set a name for the form... :-)
I already solved it 

Thanks a lot!!!

**Comment by ghiscoding** [comment]
Ok I will close this issue then
