### ISSUE TITLE
How to know which field is triggering an error 

### ISSUE THREAD

**Issue by YamilBracho** [ghiscoding/angular-validation#158]
Hi,
I have  some tabs with many fields and I am getting this error message
angular.js:14324 Angular-Validation Service requires you to have a (name="") attribute on the element to validate... Your element is: ng-model="undefined"

How do I know which field is  ?

TIA,
Yamil

**Comment by YamilBracho** [comment]
I also got this message :

angular.js:14324 Possibly unhandled rejection: Could not translate: 'Angular-Validation Service requires you to have a (name="") attribute on the element to validate... Your element is: ng-model="undefined"'. Please check your Angular-Translate $translateProvider configuration.

IN my configuration, I got 

 $translateProvider.useStaticFilesLoader({
	   prefix: 'resources/js/angular/angular-validation-ghiscoding/locales/validation/',
	     suffix: '.json'
  });

 // define translation maps you want to use on startup
 $translateProvider.preferredLanguage('en');
....

I am positive those all trasnalation files are in right path.

Any hint of rthis problem ?

**Comment by ghiscoding** [comment]
I think that you should take time to read the entire [How To](https://github.com/ghiscoding/angular-validation/wiki/HOWTO---Step-by-Step). It looks like you're missing a lot of configurations. 

Your first error is like it says, each input requires a `name` attribute in your HTML for `Angular-Validation` to work correctly. That is something like `<input name="input1" ng-model="firstName" />`

**Comment by YamilBracho** [comment]
Yes, You are absolutely right....!!
Sorry, I want to run before I walk...

Thanks!!!

**Comment by ghiscoding** [comment]
Can we close the issue then?

**Comment by YamilBracho** [comment]
Hi,
Yes, sure...
Thanks
