### ISSUE TITLE
Force a field invalid with error message

### ISSUE THREAD

**Issue by Notifium** [ghiscoding/angular-validation#159]
Hi,

First - thanks for a great module, I'm loving this.

I'm stuck on thing though. I'm trying to use the same validation routines, CSS, etc to do a "global" validation when the form is submitted. Basically, the controller makes a HTTP request to my API to validate a number of fields all at the same time. However, the errors returned could be global ("the webserver is not responding") or field-specific ("that email address is already registered"). 

I know of the remote validation technique, but I don't really want to validate each field individually.

Is there any way to trigger a single validation on form submit, and have the specific fields set as invalid with an error message?

Appreciate your help on this,
Andy

**Comment by ghiscoding** [comment]
Hello, 

`Angular-Validation` is built with validation per input based, not global based. This mean that by default, the input is invalid until the defined validation proves that it's valid, which might give you hard time for the concept you want to implement (global validation). 

There's couple of features that you might want to look into like [Wiki - Revalidate Input trigger by another input](https://github.com/ghiscoding/angular-validation/wiki/Revalidate-Input), you might also want to look at the [Wiki - Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options). 

Lastly if you look at [Wiki - Submit & Validation](https://github.com/ghiscoding/angular-validation/wiki/Form-Submit-and-Validation) and use `checkFormValidity()` from the `ValidationService`, it will call a re-validation of all the inputs.

Good luck!

**Comment by Notifium** [comment]
Thanks for getting back so quick. Hmm. I wonder: something like the following might work.

1. Have a global variable to indicate whether to validate via the server API, set this to false initially.
vm.doRemoteValidation = false;

2. Have a custom validation for the relevant fields which returns true/false + error messages based on an object/array in the controller, default these to true initially
vm.remoteValidate = {
  field1: true;
  field2: true;
}

3. Have the front-end the call the server on formsubmit, and update vm.remoteValidate:
vm.remoteValidate = {
   field1: {isValid: false, message: "failed server validation"},
   field2: true
}

4. Force revalidation: 
$scope.$broadcast('angularValidation.revalidate', "field1");
$scope.$broadcast('angularValidation.revalidate', "field2");

5. That then triggers the custom validation which returns the "false" for vm.remoteValidate.field1


Something like that anyway :-)


Thanks again for your help. Fantastic module and fantastic support!

Andy

**Comment by ghiscoding** [comment]
The idea seems reasonable, you could also try to do a `for` loop on the `$form` element instead of typing them all by hand. Remember that you have them all defined in the `$form` object. ;)

**Comment by Notifium** [comment]
Thanks so much. I got there in the end.

One useful tip i found is to tie all the ng-model attributes to vm.model.<name>, rather than just vm.<name>.

That way, i can loop through vm.model and ONLY get the actual data, not other controller properties.

Again: great module and support. Very much appreciated.

Andy
