### ISSUE TITLE
how to valid radio group

### ISSUE THREAD

**Issue by ambasador** [ghiscoding/angular-validation#166]
for example 

`<input type="radio" name="agree_1" value="true" validation="required" ng-model="form.agree_1" ng-checked="all" validation-error-to="agree">
    <label class="control control--radio" for="agree_1">
       <div class="control__indicator">Yes</div></label>
     <input type="radio" name="agree_1" value="false">
     <label class="control control--radio" for="agree_2" ng-model="form.agree_1">
      <div class="control__indicator">No</div></label>
      <div id="agree" class="validation text-danger"></div>`

its possible to check value if false display error

thank you

**Comment by ghiscoding** [comment]
reference #154

**Comment by ghiscoding** [comment]
If you want any help, please provide a Plunker, you can use the plugin [demo Plunker](http://plnkr.co/jADq7H)

**Comment by ambasador** [comment]
here is an example http://digital-legend.com/start/#/ i don't know whay plunker is not working

**Comment by ghiscoding** [comment]
I cannot see the code from there, so unfortunately I cannot help you. The reason I ask for a plunker is that I can see and play live with the code.

**Comment by ambasador** [comment]
ok validation="accepted" working fine thx

**Comment by ghiscoding** [comment]
So I will close the issue then, thanks
