### ISSUE TITLE
min_time validation. Is it possible?

### ISSUE THREAD

**Issue by mohammad-svenskalag** [ghiscoding/angular-validation#167]
Hi.

At the moment I'm solving it by a custom validation function:

vm.min_time = function () {
        // you can return a boolean for isValid or an objec (see the next function)
        var isValid = (Date.parse("01/01/2001 " + vm.event.endTime) > Date.parse("01/01/2001 " + vm.event.startTime));
        return isValid;
    }

**Comment by ghiscoding** [comment]
The `Angular-Validation` library is at the core using RegEx and if you can do it with RegEx then you can do a validation. I already added a few date type but it's hard (at least it makes a huge RegEx pattern) to validate things like leap year and other things. However one easy thing to do is to connect [Custom Validation](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions) with javascript and do whatever you want in JS, like connecting the function you described in your post.

**Comment by ghiscoding** [comment]
Closing since I gave the instructions on how to do it with [Custom Validation](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions) which is probably the only way to do it.
