### ISSUE TITLE
Check if a specific field has passed validation - possible?

### ISSUE THREAD

**Issue by mohammad-svenskalag** [ghiscoding/angular-validation#169]
Hi.

As the question in the topic. Is this possible?

Regards,

**Comment by ghiscoding** [comment]
You should take a look at all the Wiki available... [Revalite an input triggered by another Input](https://github.com/ghiscoding/angular-validation/wiki/Revalidate-Input), [Custom Validation JS](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions)

Just search by yourself

**Comment by ghiscoding** [comment]
No feedback provided, closing
