### ISSUE TITLE
Customise the validation with adding input field name

### ISSUE THREAD

**Issue by VikasSathe3189** [ghiscoding/angular-validation#170]
I'm having an issue with validation, actually I am trying to add a customised validation for between numbers [between_num] and it takes two parameters, min number, and max number. And I want to add labels in the validation as well so basically, I am trying to validate numbers between with customising error message with min and max limit input names. 

`<input type="text" name="MinimumLevel" placeholder="Enter Minimum Stock" ng-model="itemModel.MinimumLevel" class="form-control"
validation="between_num_new:{{itemModel.BaseLevel}},{{itemModel.MaximumLevel}},Base Stock,Maximum Stock />`

so I wanted to validate minimum level between Base level and maximum level with the customised message as

Needs to be a numeric value, between Base Stock and Maximum Stock. so I am sending 3rd and 4th parameter as labels in validation tag.

`case "between_num_new":
	var _ = n.split(",");
	if (4 !== _.length) throw "This validation must include exactly 4 params separated by a comma (,) ex.: between_num_new:1,5, min limit,max limit";
	r = {
		condition: [_[0] + ">=", "<=" + _[1]],
		message: "INVALID_BETWEEN_NUM_NEW",
		params: [_[0], _[1], _[2], _[3]],
		type: "conditionalNumber"
	};
	break;
	
"INVALID_BETWEEN_NUM_NEW": "Needs to be a numeric value, between {2} and {3}. ",	`

So it's working for the upper limit 
i.e if I have Base Stock = 10  and Maximum Stock= 50
Then if I input Minimum Stock = 60
Then its showing error message
But if I add  Base Stock = 10  and Maximum Stock= 50
Then if I input Minimum Stock = 40
still, it's showing validation error.
So I guess I am not able to send params properly can you please take a look how should I send these params

**Comment by ghiscoding** [comment]
You're using a lot of interpolation, that might be risky business... You should give a try with [Custom JS Validation](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions) instead

**Comment by VikasSathe3189** [comment]
Thank you for your help.
I will check  Custom JS Validation.
We can close this issue now. 
Thank you.
