### ISSUE TITLE
Validation within ng-repeat?

### ISSUE THREAD

**Issue by BradfordDJones** [ghiscoding/angular-validation#171]
I am attempting a validation of an integer field within a ng-repeat. When there are more than one item in the ng-repeat the validation fires for the first occurrences. Is this functionality supported?

**Comment by ghiscoding** [comment]
You should look at the multiple [examples](https://github.com/ghiscoding/angular-validation/blob/master/more-examples) available, I think the [dynamic example](https://github.com/ghiscoding/angular-validation/blob/master/more-examples/dynamic-form/index.html) has an ngRepeat. You should also look at all the [Wiki documentation](https://github.com/ghiscoding/angular-validation/wiki)

**Comment by BradfordDJones** [comment]
Thank you for your response. I resolved my issue. I needed to ensure that name attribute on the validated input was unique. I dynamically appended the $index of the ng-repeat to the name attribute and all validation occurs properly.
