### ISSUE TITLE
Ajax Rerquest

### ISSUE THREAD

**Issue by prasadsilicus** [ghiscoding/angular-validation#175]
I am validating data at server side by ajax on submit and I want to bind data to html field with error messages from server side..

Here is my validation response - 

{"message":"The given data was invalid.","errors":{"name":["The name email is not valid"],"email":["The email email is not valid"]}}

**Comment by ghiscoding** [comment]
I don't understand what your question is... but all the documentation is in this [wiki](https://github.com/ghiscoding/angular-validation/wiki/Remote-Validation-(AJAX)), it might help you

**Comment by prasadsilicus** [comment]
i want to display server side errors in html forms .. via error bag object is it possible...

**Comment by ghiscoding** [comment]
Yes it's possible, just read the [Wiki - Remote Validation (AJAX)](https://github.com/ghiscoding/angular-validation/wiki/Remote-Validation-(AJAX))
return the error like this `{ isValid: isValid, message: 'Returned error from promise.'}`

**Comment by ghiscoding** [comment]
cleaning up issues, closing for no feedback
