### ISSUE TITLE
min max issue or works as designed?

### ISSUE THREAD

**Issue by eduda** [ghiscoding/angular-validation#176]
validation="between_num:1,50:alt=Must be a number between (1-50)"
in <input> type="number".

if you include min="1" max="50", it appears some kind of built in validation overrides the angular-validation provided with this project in chrome (not sure of others).

is there a workaround?

**Comment by ghiscoding** [comment]
That is HTML5 validation, you can disable it by passing `novalidate` to your Form. See an [example](https://www.w3schools.com/tags/att_form_novalidate.asp)

**Comment by eduda** [comment]
I forgot to say that I did try novalidate on the form, which made no difference.

**Comment by ghiscoding** [comment]
Well you did mention that it seems to be some kind of validation outside of current lib, so I don't know what else could cause it. Also, I am no longer investing time in this lib, most of us no longer use AngularJS. However I keep it alive and I certainly accept PR if you find a fix

**Comment by ghiscoding** [comment]
I'll tag this issue as "Work as designed", all Validators receive their arguments through the validator itself (not outside). I know it could be interesting to use them for `<input/>` but I won't invest time in this lib anymore since most of us moved to Angular 2+.
