### ISSUE TITLE
Radio button required field validation not working

### ISSUE THREAD

**Issue by PrashantP25** [ghiscoding/angular-validation#181]
Hi,
    While working on a use-case where we need required field validation on radio button, we encountered that, when we add validation via code i.e using object.addValidator, on blur, validation message is not getting populated in error span. Where as when we use attribute validation it just works fine. In our use-case we use ghiscoding method to add validation for which radio buttons required field validation is not working. After investigating this issue we found a fix in ["Validation-Service.js"](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-service.js) file.
    I have created plunker (  [Click Here](http://plnkr.co/edit/VP6azmVVRy7bYdw0nhKO) )
It has all required files and 2 versions of your JS file.
ghiscodingwithfix has the fix. Please try changing references in index.html. 
   The fix that was done in file [Validation-service.js](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-service.js) are: 
   

- on line number 109, we need to replace `var validationPromise = attemptToValidate(self, event.target.value, 0);` line with `var validationPromise = attemptToValidate(self, (attrs.ctrl.$modelValue == undefined ? '' : attrs.ctrl.$modelValue),0);`

- on line number 577 we need to replace `var validationPromise = attemptToValidate(self, event.target.value, 10);` line with `var validationPromise = attemptToValidate(self, (attrs.ctrl.$modelValue == undefined ? '' : attrs.ctrl.$modelValue),10);`

Can you please accommodate these changes in repo? 
If you are ok, I will create a PR and let you know for approval

Thanks,
Prashant

**Comment by PrashantP25** [comment]
I have done the change and raised a PR. Can you check and see if you can accept this change?
PR - [181](https://github.com/ghiscoding/angular-validation/pull/182)

**Comment by ghiscoding** [comment]
Ok I have pushed a new version `1.5.27` on [NPM](https://www.npmjs.com/package/angular-validation-ghiscoding) **only**. I assume that we can close this issue then

**Comment by PrashantP25** [comment]
Thank you so much for the help
