### ISSUE TITLE
last release on bower

### ISSUE THREAD

**Issue by sergiot71** [ghiscoding/angular-validation#187]
Hi, can you post last release (1.5.28) on bower?
thanks,
Sergio

**Comment by ghiscoding** [comment]
Sorry but I already wrote that I will only update NPM as noted in the [readme](https://github.com/ghiscoding/angular-validation#project-in-life-support), I haven't logged in Bower for the past 4 years at least and I don't remember (and I don't want to) my login to access it... so NPM is the way.

Also AngularJS will be officially end of life next year (mid 2021), so I don't want to spend much time on this

**Comment by sergiot71** [comment]
Ok, thanks.
Sergio

Da: Ghislain B. [mailto:notifications@github.com]
Inviato: venerdì 7 febbraio 2020 15:43
A: ghiscoding/angular-validation
Cc: Sergio Toniutti - ERI C.E.D. Srl; Author
Oggetto: Re: [ghiscoding/angular-validation] last release on bower (#187)


Sorry but I already wrote that I will only update NPM as noted in the readme<https://github.com/ghiscoding/angular-validation#project-in-life-support>, I haven't logged in Bower for the past 4 years at least and I don't remember (and I don't want to) my login to access it... so NPM is the way.
