### ISSUE TITLE
Validation fails with nested form

### ISSUE THREAD

**Issue by prakashpun** [ghiscoding/angular-validation#188]
Hi,

My form is using another ng-form inside it. When i try to run validation service, i get following error:
`checkFormValidity() requires a valid Angular Form or $scope object passed as argument to function `

What can be a potential solution for this ? Thank you for your time.

**Comment by ghiscoding** [comment]
As mentioned on the readme page

> Project in Life Support
still accepting PR for any bug fix
Also note that only NPM will updated with new releases when PR get merged

Also note that AngularJS will be officially end of life in June 2021, might be time to move on. I haven't personally done any AngularJS in at least 2 years. So I can't help with your issue, sorry.
