### ISSUE TITLE
Custom validation does not work with angular-translate 2.18.2

### ISSUE THREAD

**Issue by ungidrid** [ghiscoding/angular-validation#189]
Recently all custom validation in my project stopped working with the following error message:
`TypeError: translationId must be a not empty string`

I've found out that the reason for this is that the angular-translate package was updated from 2.18.1 to 2.18.2 (with 2.18.1 everything is just alright).

**Comment by ghiscoding** [comment]
Then stick with that older version because there won't be anymore development in this lib. 
AngularJS is coming to an end in less than 1 year term.
