### ISSUE TITLE
Break multiple error messages into single errors and show as a bulleted list

### ISSUE THREAD

**Issue by p09** [ghiscoding/angular-validation#21]
![multipleerrors](https://cloud.githubusercontent.com/assets/11771194/7039722/6e35cba2-dde3-11e4-96e6-9419934497f8.png)

When multiple errors exist on a field they are shown in a single line. This defeats the purpose of actually showing the errors when they are all mixed up.
If i want to show the errors separately as a bullet-ed list like:
•	Must be a valid email address
•	Field is required
•	Must be at least 6 characters long

i could make a template and iterate over the set of errors for that field and show them separately. However, to actually do that i would requires the set of errors for a particular field on the view itself. is this possible?

**Comment by ghiscoding** [comment]
Sorry to say but I have a different approach than yours, I always prefer to have all the errors showing up on 1 line rather than bullets, having bullets under an input would increase the amount of space use quite drastically. I still prefer all errors on 1 line and that is how I coded it.

**Comment by ghiscoding** [comment]
Unfortunately I don't see this as beneficial, so I decided not to spend time on doing it the way you want. If you wish to look into the code and find a way that can use my way and/or your way without affecting one another, then please go ahead and I would accept pull request (as long as it does not break my current functionality). 

If you do wish to investigate the code, you can find this happening in the file `validation-common.js` under the `validate()` function and the current code that make all the errors to show up on the same row comes from the line 325 (currently) with the code of `... message += ' ';`
