### ISSUE TITLE
Define global "debounce" value

### ISSUE THREAD

**Issue by iltera** [ghiscoding/angular-validation#25]
I couldn't find anything about defining a global value for debounce in the docs. Is there a way to change it without messing with the source code?

**Comment by ghiscoding** [comment]
If you are using the Directive then unfortunately there is no global way of setting it, but if you are using the Service you can use the `setGlobalOptions`, see the [Examples-Services](https://github.com/ghiscoding/angular-validation#examples-service). You could actually try that global set function, not sure it would work within the Directive but it's worth trying... something like this perhaps `new validationService().setGlobalOptions({ debounce: 1500})`, I haven't tried it inside the Directive, so you might want to give it a try... Let me know if it works, I will update my docs if it does.

If first option does not work and you want to change the code, the default debounce is actually set inside the `validation-common.js` file on line 17 `var INACTIVITY_LIMIT = 1000;` 

Good luck

**Comment by ghiscoding** [comment]
Added `$validationOptions` which will help you do exactly what you want... Take a look at the doc on the new section [Global Options](https://github.com/ghiscoding/angular-validation#global-options)

**Comment by iltera** [comment]
Thank you for your fast answer, and light speed update for the issue :+1:
