### ISSUE TITLE
unbind 'blur' in cancelValidation()

### ISSUE THREAD

**Issue by LennyLip** [ghiscoding/angular-validation#28]
I think, [obj.commonObj.elm.unbind('blur');](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-service.js#L248) in cancelValidation() is wrong.

FE, I have a angular-strap tooltip, which triggered on blur event. When i have input field with  validation="max_len:50" and empty value when lost focus blur does not work and tooltip does not disappear, because blur is unbind.

**Comment by ghiscoding** [comment]
The biggest reason of the `cancelValidation()` is that I don't want to annoy the user on an empty form, not doing this would mean showing all errors directly at start, which is the reason of the `cancelValidation()`

You should perhaps try using the `checkFormValidity()`, that would trigger all the errors while also checking the form validity. If that is not what you are trying to do, then I might have misunderstood your question.

**Comment by ghiscoding** [comment]
Also by the way, the error messages are only showing if the element is `$dirty`, `$touched` or if the form has been submitted.

**Comment by LennyLip** [comment]
Ok, i've created http://plnkr.co/edit/x6AI9U8mGF0P4NMVmzvR?p=preview

see second input , tooltip does not disappear, because blur is unbind by cancelValidation(). but in first input all ok, because "required".

**Comment by LennyLip** [comment]
@ghiscoding 
btw, you wrote "unbind onBlur event, if not it will fail when input become dirty & empty".
may be we can use ($setPristine())[https://docs.angularjs.org/api/ng/type/ngModel.NgModelController]; instead unbind?

**Comment by LennyLip** [comment]
renew this comment

@ghiscoding 
you wrote "// unbind onBlur event, if not it will fail when input become dirty & empty"

I could be wrong, but may be we can something like: add "watch" and when input empty set [$setPristine();](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController) for input. 

?

**Comment by ghiscoding** [comment]
This should fix it...

**Comment by LennyLip** [comment]
it is does not help, see http://plnkr.co/edit/x6AI9U8mGF0P4NMVmzvR?p=preview with 1.3.19

**Comment by ghiscoding** [comment]
Well I am not doing a full unbind anymore so I don't think it comes from my end, you could even remove the unbind from my code and it would still work. Try debugging it and see what can cause it... If you want to debug my code, you should use the non-minified versions.

**Comment by LennyLip** [comment]
i h've been commented this line and tooltip is disappeared.
//elm.unbind('blur', blurHandler); // unbind onBlur event so that it does not fail on a non-required element that is now dirty & empty

also, i don't have any "fail on a non-required element that is now dirty & empty" (with dirty & empty input).

**Comment by LennyLip** [comment]
hm, i've been debug 
elm.unbind('blur', blurHandler);

and i see, that blurHandler is undefined. (thats why ubnind disable all blur handlers)/

i think,  it because cancelValidation() run before elm.bind.

**Comment by ghiscoding** [comment]
it is not suppose to be undefined, it's a global variable and is set at the bind calling, unless it's unset on first pass. You could try commenting out that line (unbind) and see if that really is your problem. I still need to unbind it somehow because I might end up with 50 calls at the end.

**Comment by LennyLip** [comment]
http://savepic.net/6756572.png

**Comment by LennyLip** [comment]
we have "elm.bind('blur', blurHandler = function() {" on 85 line, but "cancelValidation();" is call on 72 line in one function "function attemptToValidate(value) {".

so, we call "elm.unbind('blur', blurHandler); " with undefined blurHandler.

**Comment by LennyLip** [comment]
> You could try commenting out that line (unbind) and see if that really is your problem. 

it's really my problem
https://github.com/ghiscoding/angular-validation/issues/28#issuecomment-94828994

**Comment by ghiscoding** [comment]
Could you try the following
```javascript
// replace this line
elm.unbind('blur', blurHandler);

// with these lines
if(typeof blurHandler !== "undefined") {
  elm.unbind('blur', blurHandler);
}
```

I am at work and I cannot really test it, it would help if you can test it with your code too.

**Comment by LennyLip** [comment]
@ghiscoding 
seems, it is works, thank you!

**Comment by ghiscoding** [comment]
Ok I will make more tests tonight and will also fix another open issue at the same time. You should expect to see the new code and the minified code on the next version 1.3.20 later tonight.

Thanks

**Comment by ghiscoding** [comment]
As promised, I push the code after testing... Hopefully that works for you
