### ISSUE TITLE
Recent code commit not working

### ISSUE THREAD

**Issue by p09** [ghiscoding/angular-validation#29]
The plunker http://plnkr.co/edit/WSjjdpVC9ck3NUw7iuKy?p=preview is not working for some time. Its referring to your git repo for validation js.
 Previously you had mentioned (in https://github.com/ghiscoding/angular-validation/issues/26) that you had committed the required changes for this issue but it seems its still not fixed.
With an older version (version 1.3.15) of your validation code this works but fails for your latest one 1.3.20.

**Comment by ghiscoding** [comment]
I answered you in the other post, please don't open a new issue for the same problem. I can re-open the issue #26 if it's really broken but it's not.
