### ISSUE TITLE
Remove validation errors for form fields 

### ISSUE THREAD

**Issue by p09** [ghiscoding/angular-validation#30]
Currently the removeValidator() method provided in the validationService removes the validation message from the form validation summary but the error still continues to be shown next to the validated field.
On removing validator the error attached to field should also be removed.

**Comment by ghiscoding** [comment]
It might be nice to have some of your help sometimes, instead of just posting issues... that is what a community is for, helping each other.

**Comment by ghiscoding** [comment]
Looking at my code, it already does the effect that you are asking for. You can see and test this on my demo sample in the Service page. If you really still have issues, then make a plunker describing your problem.

**Comment by p09** [comment]
I was wrong. I had some code changes at my end because of which i was getting this issue. Once i tried to recreate the issue from scratch i realized i had made a mistake.
Sorry. You can please go ahead and close this issue.
