### ISSUE TITLE
Script order matters

### ISSUE THREAD

**Issue by aaronbc** [ghiscoding/angular-validation#36]
It looks like the order that the scripts are included matters.  The documentation highlights the correct order:
validation-directive.js
validation-service.js
validation-common.js
validation-rules.js

But the bower.json file has a different order which for some reason prevents angular from finding the validation module.  This is an issue when using a tool like grunt-wiredep which automatically inject script includes based on the bower.json files.

**Comment by ghiscoding** [comment]
Yes the order matters a lot. the `validation-directive.js` has to be called first and the rest can come in whatever order after. I was wondering why that matters to you but I see that the `bower.json` is in fact not up to date indeed, You can also see the order of the files in the `gulpfile.js` where I minify and concatenate the scripts into 1 file.

I will fix it in the next coming version. Thanks for bringing it up.

**Comment by ghiscoding** [comment]
Should be fixed in latest v1.3.24, in case of any other problems, let me know

Thanks for feedback
