### ISSUE TITLE
custom validation

### ISSUE THREAD

**Issue by mohdmasd** [ghiscoding/angular-validation#4]
Hi, thanks for this fun library.

How can I add custom validators? It doesn't seem possible now.
Is it possible too to expose a validation service instead of relying only on directive ?

**Comment by ghiscoding** [comment]
Added the functionality in version 1.3.7

**Comment by geemang2000** [comment]
If I have to make a remote call for validation. Is that possible. Is there a simple example of a custom validation rule?

**Comment by ghiscoding** [comment]
Your question is not fully clear to me, are you talking about validation call from within a controller? If that is the case, then use the [Angular-Validation Service](https://github.com/ghiscoding/angular-validation/wiki/Working-Service-Examples). You can find all yours answers in the [Wiki](https://github.com/ghiscoding/angular-validation/wiki) section, so please go and read them.
