### ISSUE TITLE
date_euro_long does not seem to work without required

### ISSUE THREAD

**Issue by cwallervand** [ghiscoding/angular-validation#42]
The validator date_euro_long does not seem to workwithout also using the required validator. 

E.g the date 29.12.1986 does not validate when validation="date_euro_long:alt=sometext" but does validate when validation="required|date_euro_long:alt=sometext"

The error might apply to other date validations as well

**Comment by ghiscoding** [comment]
Sorry but I don't see what your problem is... when trying on my Live Demo plunker and changing it to your validation, it does validate it and the `alt` text is showing when invalid which is normal and working as expected. Don't know how to upload print screen here, else I would show you as well

**Comment by ghiscoding** [comment]
Showing invalid, you can see on the left, the html code for it which does not have `required`
![dateeuroerror](https://cloud.githubusercontent.com/assets/643976/8360578/92b9d7bc-1b3b-11e5-8867-be5649811e67.jpg)

And the once I type in the valid date, the error (in this case the `alt` text) goes away and the border turns green. 
![dateeurovalid](https://cloud.githubusercontent.com/assets/643976/8360577/929011f2-1b3b-11e5-862a-145960ca43d6.jpg)

So I don't see any problems on my side

**Comment by ghiscoding** [comment]
Could you give some feedback so I could close this issue or investigate more if need be... Thanks

**Comment by cwallervand** [comment]
Did some tests today and couldnt find any issues so just close it

Den fredag 26. juni 2015 skrev Ghislain B. <notifications@github.com>
følgende:

**Comment by ghiscoding** [comment]
Ok great, thanks !

**Comment by ghiscoding** [comment]
BTW if you use and like the project, you can click on the `Star` and make it a favorite. Would be nice to reach a 100 :)
