### ISSUE TITLE
Problem regex

### ISSUE THREAD

**Issue by zaideygrek** [ghiscoding/angular-validation#43]
Hello and thank you in advance for your validation system.

I have a problem using validation regex, validation is strange, sometimes it's good and sometimes not. Here is the code I use, I do a mistake?

```javascript
@validation
  .setGlobalOptions({ debounce: 1500, scope: $scope })
  .addValidator('password', 'regex:password23A:=/(?=(.*[A-Z]){1,})(?=(.*[a-z]){1,})(?=(.*[0-9]){1,})(?!.*\|).{8,20}/g:regex|required')
  .addValidator('passwordConfirm', 'match:user.item.password,mot de passe|required')
```

Thank you.

Alex

**Comment by ghiscoding** [comment]
What is that suppose to validate? I don't know what your Regex is suppose to do, so can you give examples... 

The way I run the regular expression is to get the pattern string and put it inside `regex = new RegExp(pattern, 'i');` which mean in your case that it would do 

```javascript
regex = new RegExp("/(?=(.*[A-Z]){1,})(?=(.*[a-z]){1,})(?=(.*[0-9]){1,})(?!.*\|).{8,20}/g", 'i');
regex.test(value);
```

I am not sure if your code is valid or not, you can try it in javascript and see what happen.

**Comment by zaideygrek** [comment]
Thanks,

I try with this code and it's exact 

    console.log (/^((?=.*\d)|(?=.*\W))(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{8,20}$/.test('password23A'))

but not with this one

    regex = new RegExp("/(?=(.*[A-Z]){1,})(?=(.*[a-z]){1,})(?=(.*[0-9]){1,})(?!.*\|).{8,20}/")
    console.log regex.test("password23A")

**Comment by ghiscoding** [comment]
Ok I think that I know, I use the RegExp object as a string argument, first you don't need the `/` at the beginning and end... and second since it's a string, you need to escape all the `/` with `//`, but in your case since you should remove them, I think there is nothing else to espace.

**Comment by zaideygrek** [comment]
Thank you for the explanation, it's perfect.

**Comment by ghiscoding** [comment]
Updated the [Wiki - Regular Expressions (Regex)](https://github.com/ghiscoding/angular-validation/wiki/Regular-Expressions-(Regex)) for less confusion.

Thanks for the feedback

**Comment by ghiscoding** [comment]
BTW if you use and like the project, you can click on the `Star` and make it a favorite. Would be nice to reach a 100 :)

**Comment by ghiscoding** [comment]
Please note that I completed rewrote the custom regular expression implementation, I didn't like the first approach and decided to rewrite it.

The issue you brought up originally had an influence on how I really wanted it to work and so I decided to rewrite it... So thanks for the previous feedback :)

So please update and use the new version [1.3.35](https://github.com/ghiscoding/angular-validation/releases/tag/v1.3.35) and see the documentation on the new [Wiki - Regular Expression Pattern](https://github.com/ghiscoding/angular-validation/wiki/Regular-Expression-Pattern)
