### ISSUE TITLE
Enhancement: Event when validation summary is changed. 

### ISSUE THREAD

**Issue by cwallervand** [ghiscoding/angular-validation#49]
Hi. It would be great if there was an event listener  in the service for changes on the validation summary.

E.g: 
```
validationService.onValidationSetChanged(function(validationSummary){
  ..........
});
```

**Comment by ghiscoding** [comment]
Hello, I'm not sure to fully understand your question, maybe it's because I didn't have my morning coffee yet. I don't understand how that would work and what kind of events would be sent. 

Just to review the process, the validation summary is filled on page load and reviewed each time the validation comes in play. Where in the process do you want events?

**Comment by cwallervand** [comment]
My specific scenario is that I have a multi step form. The form can get very long before proceeding to the next step so I woul like to show a message next to the "Next" button if the form is not valid. To do this I would need to know when the form is valid / invalid (probably using the $valid property) so that I can remove the message as soon as the form is valid (e.g. before pressing the "Next" button). 

Hope that was a bit more understanding

**Comment by ghiscoding** [comment]
You can simply use the `$invalid` property with `ngDisabled` that would look like this `<button type="submit" ng-disabled="form1.$invalid">Save</button>` and if you want to do the inverse then just use a not (!) in front `ng-disabled="!form1.$invalid"`, you can see an example in the [Wiki - Form Submit and Validation](https://github.com/ghiscoding/angular-validation/wiki/Form-Submit-and-Validation), it's also like that in the [Live Demo on Plunker](http://plnkr.co/jADq7H)

**Comment by cwallervand** [comment]
Yeah....my bad, thanks for the feedback though.
