### ISSUE TITLE
Can i setup a validation that is conditional ?

### ISSUE THREAD

**Issue by rluiten** [ghiscoding/angular-validation#52]
I've tried to use addValidator() and removeValidator() and have it working but its pretty awful IMO.
Going in I had almost expected that validation rules on a field would be disabled if ng-required was false. But then maybe that was an unreasonable expectation.

Maybe I am just missing something obvious.

We have quiet a few forms were some fields appear and are required to have a value if a checkbox is selected.

Thanks for reading,
Rob.

**Comment by ghiscoding** [comment]
The function of `removeValidator()` is made to completely remove it, it's not made for what you want to do. 

If you want to validate a field only after your checkbox is selected, then you should add the validation on your input but make your input disabled with `ngDisabled` and only make it enable once the checkbox is clicked. Angular-Validation does not validate a field that is disabled, but will validate if it becomes enable. You can see that in the demo I made on the [Live Plunker Demo](http://plnkr.co/jADq7H) the last field.

This is the code from the demo with a radio button, just change the radio to a checkbox and you are good to go
```html
<div class="form-group">
            <label for="input4">ngDisabled =></label>
            ON <input type="radio" id="radioDisableInput4_on" ng-model="vm.disableInput4" value="on" ng-init="vm.disableInput4 = 'on'">
            OFF <input type="radio" id="radioDisableInput4_off" ng-model="vm.disableInput4" value="off">
            <input type="text" class="form-control" name="input4" placeholder="alpha_dash|min_len:2|required" ng-model="vm.input4" validation="alpha_dash|min_len:2|required" ng-disabled="vm.disableInput4 == 'on'" />
        </div>
```

**Comment by rluiten** [comment]
That makes perfect sense [it was something I was missing], all the code here currently uses conditional on ng-required - which works but isn't as intention revealing. We still have a fair bit of not using angular-validation yet.

One further question, I have modified this form to use ng-disabled and it works and gets rid of the mess I had made before. 

However one further hiccup, by using ng-disabled with the right condition the field appears correctly and is required correctly but it is marked in red with validation message on first appearance. The state of enabled field shows up with $pristine true and $valid false, now this is the same as the other fields that were never disabled to start with, but the other field do not show the validation markings until after being dirty, or submit has run which executes checkFormValidity() to flag all fields for the user.

**Comment by ghiscoding** [comment]
I believe that is normal behavior to have the red border, because the field is really invalid since it's `required`. What you have to do is to change your CSS to only show red border on dirty. 

This is part of my CSS to do that
```css
/* invalid & (dirty or touched) => red -- CSS3 only */
.ng-invalid.ng-dirty:not(:focus),
.ng-invalid.ng-touched:not(:focus) {
    border-color: #e74c3c;
}

/* valid & dirty => green */
.ng-valid.ng-dirty.ng-touched {
    border-color: #2ecc71;
}
```

If you have no more questions and this fixes your problem, please close this issue. Thanks

**Comment by rluiten** [comment]
Ill restate my comment, maybe I did not express myself sufficiently.

The other fields all have validation="required", and are not showing the validation when they are shown. It is common to not show it if the control is still pristine$ I believe this is why you provide the checkFormValidity() to force them to be visible if for example if someone wants them all to appear if someone presses submit button.

Its just the enabled form field is shown differently from other fields that also required on the form, it is shown invalid when others are not yet.

**Comment by rluiten** [comment]
Hmm interesting, this field that has been enabled is marked $touched is true.

**Comment by ghiscoding** [comment]
Ah now I think I know what you mean. Yes that is how I coded it, when you enable it, I validate and touch the item, if it's required then the error message will show right away. You can see that in the live demo.

I should maybe change that and only show it right if the global option of `preValidateFormElements` is True. Looks like I'm never done with this library :'(

**Comment by ghiscoding** [comment]
When a field get re-enable, I run the validation on it and I also mark it as `$touched`, which is what you found out.

I found the code where it does that, I'll have to change to few things to do as said in my previous comment: 
*I should maybe change that and only show it right if the global option of preValidateFormElements is True.*

I will have to modify my Protractor tests also, since it changes a few things and it will fail. I will see if I can push that in the next couple hours or tomorrow.

**Comment by rluiten** [comment]
Don't do it on my account we are weeks from next deployment at moment.

Extra note, as a test I added an ng-disabled="false" to one of my normal form fields and it also gets the validation shown immediately. Which make sense in the light of your comments.

**Comment by rluiten** [comment]
My colleague just asked me a related question, he is aware of a few forms where a field that is normally optional becomes a required field when a checkbox is set to true. Does this scenario require the use of the addValidator() removeValidator() methods ?

As a side note, i think making removeValidator() not crash if there isnt a validator allready there would be a good thing.

**Comment by ghiscoding** [comment]
I already got something close to working, but I want to take a break now, it will not validate automatically anymore (unless you have the global options `preValidateFormElements` is True). Which is how I should have coded it at first, it makes more sense that way. 

What do you mean by `removeValidator()` crash? What are your function arguments?

The `removeValidator()` was created to completely remove all validators to the field. You could use the `addValidator()` to add it back, but playing with those 2 functions might not always be the best. If you want to dynamically add validation, you could also do it yourself through Angular interpolation, you could probably do something like this: `<input type="text" name="field2" validation="{{vm.isRequired}}" />` where the `vm.isRequired` is set somewhere in your controller or in your view by another field, up to you. You just need to be creative and find a solution, there is multiple ways to do it, just think about it and have fun finding a solution... 

I can't put everything into Angular-Validation, it's already doing a lot, I don't want to over complicate it, with extra features that are not always necessary.

**Comment by rluiten** [comment]
Ahh i feel stupid now :), while I've used angular a bit now, still not always doing things the easy way.

**Comment by rluiten** [comment]
I have tried out the interpolation to validation.
I cant get it to work at all, made an example, maybe I have missed something again.
http://plnkr.co/edit/tj4ZXo0CpU3EnMIhdAzI?p=preview

**Comment by ghiscoding** [comment]
I used your plunker demo to test it out and you were correct, the interpolation wasn't working correctly, but now it does :)
You can find a demo under the folder `angular-validation/more-examples/interpolateValidation` which is based on the plunker demo you did. 
I also fixed your [plunker](http://plnkr.co/edit/rtSPU8PLzCgx6tARmH2T?p=info) if you want to see it there.

And finally, I also fixed the red border that was showing at the beginning, the behavior is now to still pre-validate the field but without showing the error message right away (unless you defined the global option of `preValidateFormElements ` to True).

So please use the new version [v.1.3.38](https://github.com/ghiscoding/angular-validation/releases/tag/v1.3.38)

Thank you for the great feedback!
You should hire me, you find the bugs and I fix the bugs..lol

**Comment by rluiten** [comment]
This looks good so far.
I can't hire you :) I am a contractor, and the project I am on might well be imploding due to political reasons in the near future. Though the software is finished enough to be useful thankfully.

**Comment by ghiscoding** [comment]
Oh well, good luck with your project. Hopefully you'll use my library for all future projects ;)

**Comment by ghiscoding** [comment]
Just so you know, another person raised a small issue just after my previous version, so [v.1.3.39](https://github.com/ghiscoding/angular-validation/releases/tag/v1.3.39) was pushed 2min ago, so 1.3.38 is already outdated. I hope it's the last one for long time though.

**Comment by rluiten** [comment]
I noticed the 1.3.39 update and laughed, but sounds like a good fix to.
If your library gets popular i am sure more corner cases and such will be discovered.

I have the v1.3.39 installed in our project now, and the validation behaviour is much nicer now don't get the warnings till after submit is pressed which I think is a nice. Also the conditional validation with interpolation in two of our forms has made them markedly simpler.

One of the reasons your library IMO is better than the other 5 I had looked at is yours reduces the markup complexity and the coding complexity. Some of the libraries I looked at I had to do as much work as if I was handling it all myself anyway.

**Comment by ghiscoding** [comment]
My end goal was simplicity :)

Having more people using it, is great also for the fact that lot of features came from suggestions of others. You brought up `ControllerAs`, some persons even took the time to add new locale translation as well. For a first open source tool, I think it's a success :)

Alright time to sleep in Canada, it's pass midnight. Cheers from the other end ;)
