### ISSUE TITLE
Change support HTML text

### ISSUE THREAD

**Issue by dungvu-qe** [ghiscoding/angular-validation#54]
I need binding translate text with html code format like : "Required \<br />" . Your lib still use function errorElm.text(errorMsg), this can not set html code, could you change it to errorElm.html(errorMsg). 

// invalid & isDirty, display the error message... if <span> not exist then create it, else udpate the <span> text
      if (!!attrs && !attrs.isValid && (isSubmitted || self.ctrl.$dirty || self.ctrl.$touched)) {
        (errorElm.length > 0) ? errorElm.text(errorMsg) : elm.after('<span class="validation validation-' + elmInputName + ' text-danger">' + errorMsg + '</span>');
      } else {
        errorElm.text('');  // element is pristine or no validation applied, error message has to be blank
      }

**Comment by ghiscoding** [comment]
Wow you should have told me before I created my new revision... 
Why are you using html code anyway?

**Comment by dungvu-qe** [comment]
Sorry, when add your new lib version, I have some minor UI bugs, and found
this issue. It not a major issue, no need new revision for this :)

-- 

*Dung Vu | Developer | Amigo Quant Edge JSC*

mobile: +849 0896 6639 <//mobile:%20+849%200896%206639>
email: dung.vu@quant-edge.com
skype: dung.vt

Amigo Quant Edge JSC
Suite #503, IPH Building
241 Xuan Thuy Street, Cau Giay Dist
Hanoi, Vietnam

tel: +84 (4) 7300 8999 <//tel:%20+84%20(4)%207300%208999>
fax: +84 (4) 7300 3999 <//fax:%20+84%20(4)%207300%203999>
web: www.quant-edge.com
------------------------------

This message (including attachments, if any) is confidential, may be
privileged and is intended for the above-named recipient(s) only. If you
have received this message in error, please notify me by return email and
delete this message from your system. Any unauthorized use or disclosure of
this message is strictly prohibited.

Amigo Quant Edge JSC assumes no responsibility for errors, inaccuracies or
omissions in these materials, and does not warrant the accuracy or
completeness of the information contained within these materials. Amigo
Quant Edge JSC shall not be liable for any special, indirect, incidental,
or consequential damages, including without limitation losses, lost
revenues, or lost profits that may result from these materials.

**Comment by ghiscoding** [comment]
Yes you should have told me earlier, I don't like having 2 revisions in the same day, doesn't look too professional :(
The reason of why the Revision exists is for Bower & NuGet package manager, without Revision, you could not get latest code... unless you download directly from Github.

I will push another revision after finishing the End-to-End tests with Protractor, it takes over 15min to run all tests.

**Comment by ghiscoding** [comment]
Now pushed into version [v1.3.39](https://github.com/ghiscoding/angular-validation/releases/tag/v1.3.39)

**Comment by dungvu-qe** [comment]
you're the best :+1:

**Comment by ghiscoding** [comment]
If you like the project, you could also click on the **Star** on top ;)
Hope to reach 100 followers :)
