### ISSUE TITLE
TextArea validation

### ISSUE THREAD

**Issue by LennyLip** [ghiscoding/angular-validation#56]
I searched, but did not find an answer

I have:
     textarea name="description" validation="min_len:50|max_len:2000|required"

When i type Enter (new line) validation error is fired. Why?

**Comment by ghiscoding** [comment]
It's only suppose to fire after the user stop typing, by default it's 1sec. Even on my plunker demo, it doesn't do what you just describe, try my demo and you'll see. Did you define any Global Variable of Angular-Validation?

If you could make a plunker demo, that would help in debugging, without that it's hard to help you more

**Comment by LennyLip** [comment]
http://plnkr.co/edit/2jr6rAyL9GA6fMGfiVl7?p=preview
![123](https://cloud.githubusercontent.com/assets/955994/9155522/1677a232-3ec3-11e5-9e4a-44fefa975ead.png)

**Comment by LennyLip** [comment]
![124](https://cloud.githubusercontent.com/assets/955994/9155550/32c9fbaa-3ec4-11e5-8273-a163f3e7649d.png)

**Comment by ghiscoding** [comment]
So your problem is around the fact that when you do a ENTER, the `min_len` becomes incorrect. Do I understand correctly?

**Comment by ghiscoding** [comment]
Ok you were right, I found out that a new line (ENTER) is breaking the Regex that I was using on `min_len`, `between_len` and `max_len`.

On `min_len`, I was using this Regex  `/.{15,}$/` but this doesn't work with a new line
Found out that I could do this instead  `/(.|[\r\n]){15,}$/` and that is working with a new line

I will update the 3 rules in the `validation-rules.js` and that should fix it. 

https://regex101.com/#javascript

![regex](https://cloud.githubusercontent.com/assets/643976/9155873/37ee9dea-3e95-11e5-925f-f06535c28d7e.jpg)

**Comment by ghiscoding** [comment]
Should be all good now... thanks for the feedback!

**Comment by LennyLip** [comment]
Many thanks for help! 
All ok now.
