### ISSUE TITLE
invalid return value with function String.format()

### ISSUE THREAD

**Issue by dungvu-qe** [ghiscoding/angular-validation#65]
this lib override function String.format but in this case is not correct:  
console.info(String.format("ID: {0} with value: {1}", 0, 1));
//return "ID: {0} with value: 1"

**Comment by ghiscoding** [comment]
Good catch, thanks for the feedback. A fix is coming after running all my Protrator tests. Thanks

**Comment by ghiscoding** [comment]
Should be good now, if not then please let me know.. Thanks
