### ISSUE TITLE
Integration with angularjs-dropdown-multiselect

### ISSUE THREAD

**Issue by gustavolira** [ghiscoding/angular-validation#66]
Hi,
It would be nice if this plugin had support with angularjs-dropdown-multiselect. 
https://github.com/dotansimha/angularjs-dropdown-multiselect

**Comment by newpaulinhu** [comment]
+1

**Comment by RobsonMathias** [comment]
+1

**Comment by dpr001** [comment]
+1

**Comment by JosielSantos** [comment]
+1

**Comment by trsenna** [comment]
+1

**Comment by leowebx** [comment]
+1

**Comment by ghiscoding** [comment]
Thanks for the suggestions but I don't currently support 3rd addons, which is the case for both your requests #66 and #67. If you want to help and make a pull request, that would be great else I don't really have much of my personal time to spend on something that I don't use myself. I have other priorities.

Talking more about the subject, 3rd party addons are in most cases, which seems true for both your requests, are using wrapper and change the input value input something completely different, most of the time new `<div>`, my library is for getting values of something that exist on current element, I don't really want to spend my time on finding something that might exist somewhere else in the DOM. Also trying to find and validate a new element that would need to be found in the DOM, would be a performance killer and would also be completely different from 1 addon versus another (for example your `ng-tags-input` doesn't have the same wrapper as `dropdown-multiselect` does).

So unless you want to spend the time on working on this, I don't really want to do that. And I would prefer to accept something that is generic, meaning that it would work with any type of 3rd party addon, but I wouldn't know how deal with that at this point.

Oh and having your friends to do `+1` won't change much.

**Comment by ghiscoding** [comment]
Thinking a bit more about this and what could possibly be done to make it more generic is maybe to have a common attribute that is bind to the result, then inside the validation I could use that result to validate. The new attribute would have to be name that could be re-used no matter what 3rd party addon you use.

Something like this maybe (where `validation-result` would be a new attribute)
```javascript
<div 
    ng-dropdown-multiselect="" 
    options="example1data" 
    selected-model="example1model"
    validation="required"
    validation-result="example1model">
</div>
```

or your other 3rd party addon (with again the new attribute `validation-result`)
```javascript
<tags-input ng-model="example1model"
    validation="required"
    validation-result="example1model">
</tags-input>
```

That might work and could still be generic with common attribute which Angular-Validation would know where to get his result.

**Comment by gustavolira** [comment]
Thank you for your help.

It's a good idea, I will try implement this.

2015-09-09 9:44 GMT-03:00 Ghislain B. <notifications@github.com>:

**Comment by ghiscoding** [comment]
what kind of validation are looking at doing, just `required` or a specific value(s)? Your ngModel seems to return an array of indexes (id), for a `required`, it's manageable but for a specific value the Angular-Validation would not know what to do with it...

**Comment by ghiscoding** [comment]
This is coming, I hope all these `+1` are going to change into +1 **Star** on the library.

**Comment by ghiscoding** [comment]
Done.. You can check the [Wiki - 3rd party addon validation](https://github.com/ghiscoding/angular-validation/wiki/3rd-Party-Addons). 

I will have a demo soon on Plunker as well, but for now you can look at code sample in the folder `/more-examples/addon-3rdParty/` it has 3 different 3rd party addons.

Now all of your `+1` please change them to **Star**

**Comment by ghiscoding** [comment]
The [Plunker Demo](http://plnkr.co/4qdsxAeV7zSRUf8Nk2u0) is now available

**Comment by jinalkachariya26** [comment]
Demo is not working. Please provide a solution.

**Comment by ghiscoding** [comment]
The demo is not working simply because 1 of the 3rd party lib link changed.
The [Wiki - 3rd party addons](https://github.com/ghiscoding/angular-validation/wiki/3rd-Party-Addons) is still valid.
