### ISSUE TITLE
Integration with ng-tags-input

### ISSUE THREAD

**Issue by gustavolira** [ghiscoding/angular-validation#67]
Hi,
It would be nice if this plugin had support with ng-tags-input
https://github.com/mbenford/ngTagsInput
Thank you

**Comment by newpaulinhu** [comment]
+1

**Comment by dpr001** [comment]
+1

**Comment by JosielSantos** [comment]
+1

**Comment by ghiscoding** [comment]
This is coming, I hope all these `+1` are going to change into +1 **Star** on the library.

**Comment by ghiscoding** [comment]
Done.. You can check the [Wiki - 3rd party addon validation](https://github.com/ghiscoding/angular-validation/wiki/3rd-Party-Addons). 

I will have a demo soon on Plunker as well, but for now you can look at code sample in the folder `/more-examples/addon-3rdParty/` it has 3 different 3rd party addons.

Now all of your `+1` please change them to **Star**

**Comment by ghiscoding** [comment]
The [Plunker Demo](http://plnkr.co/4qdsxAeV7zSRUf8Nk2u0) is now available
