### ISSUE TITLE
server side validation

### ISSUE THREAD

**Issue by tomtommorrow** [ghiscoding/angular-validation#70]
Sorry, this isn't really an issue rather a question.  I haven't found any documentation on whether this library has hooks for server side validation.  e.g. pass in an array of errors that match the current form fields names.

Great library BTW!  Works really well and from what I have gone over so far, the code looks really clean.  Nice job.

**Comment by ghiscoding** [comment]
For Server Side Validation, this is what I have [Wiki - Remote Validation](https://github.com/ghiscoding/angular-validation/wiki/Remote-Validation-(AJAX))

**Comment by ghiscoding** [comment]
Does that answer your question? If so can we close the issue?

Thanks for the comments by the way ;)

**Comment by tomtommorrow** [comment]
Sorry.  Just looked over your response.  I guess i need to read the documentation better.  Yes, i think that will work well.  Thanks again!

**Comment by ghiscoding** [comment]
No worries, all good. Nice to know lot of people are using my library ;)
