### ISSUE TITLE
Global custom validator

### ISSUE THREAD

**Issue by gustavolira** [ghiscoding/angular-validation#72]
Would be nice if was possible to create Global custom validator for instance at Angular Config or Angular Run method instead of define them at a specific controller or at html using pattern.

**Comment by ghiscoding** [comment]
Sorry but I don't see any advantages on doing so. 
A form with inputs to validate won't exist without a Controller anyway, so what would be the point of having validators in the Angular Config? The Angular Config section should only be used for presetting some config used across various controllers, validators shouldn't be part of that, they are not settings.

Unless I'm not understanding your question, if so please give more details and/or code examples, else I would close it.

**Comment by gustavolira** [comment]
I have a rule validation that I need to use on different places, base on this I will need to put the same validation in several controllers, duplicating the code

**Comment by ghiscoding** [comment]
Though I still don't think Validation should go in the global Angular config. What you should do instead is define constant variable in your that config and just re-use that constant through out your controllers or wherever else you need them. That is if I understood correctly your problem.
