### ISSUE TITLE
Some improvements to the French translation

### ISSUE THREAD

**Issue by littletower** [ghiscoding/angular-validation#73]
This is really a minor thing but in the French i18n file the dates messages use the English format dd-mm-yyyy or dd/mm/yyyy. In French you tend to use the following format jj-mm-aaaa or jj/mm/aaaa since d-day translated is j-jour, m-month is m-mois, y-year is a-année.

cheers

**Comment by ghiscoding** [comment]
Ah oui c'est vrai je n'ai pas fait attention a ça au début, j'ai tout simplement copier les phrases en anglais et traduit ligne par ligne. Merci pour l'info, j'allais justement faire une nouvelle révision sous peu pour ajouter une nouvelle fonctionalité. Alors je vais inclure ce changement dans la prochaine version, peut-être aujourd'hui si tout va bien.

Si tu aimes la librairie, tu peux également cliquer en haut sur **Star** si ce n'est pas déjà fait.
Bonne journée.

**Comment by ghiscoding** [comment]
Voilà!!!  implémenté dans la version `1.4.9`

**Comment by littletower** [comment]
Cool!
Je vais traduire en allemand et en luxembourgeois(!!) très prochainement, t'es intéressé de les avoir?

**Comment by ghiscoding** [comment]
Ah oui certainement, c'est toujours intéressant d'avoir de nouvelles traductions. Ca aide la communauté également :)

Merci bien ;)

**Comment by ghiscoding** [comment]
Rebonjour je suis simplement curieux... est-ce que ca tient toujours pour les nouvelles traductions? :)

Il est également à noter que dans la dernière version [1.4.10](https://github.com/ghiscoding/angular-validation/releases/tag/v1.4.10) que je viens de pousser, j'ai fait quelques petits changements sur certain messages pour qu'il passe le mode de `Sanitize`, il y a donc quelques petites modifications a faire attention.

Merci de l'aide :)

**Comment by littletower** [comment]
Salut, oui ça tient toujours, mais je n'ai pas encore eu le temps, faudra patienter un peu :)
Je porterais attention aux modifications, merci!
