### ISSUE TITLE
Issue with UI Bootstrap datepicker

### ISSUE THREAD

**Issue by sandeepthomas** [ghiscoding/angular-validation#74]
I'm using latest ui bootstrap (0.14.2). I need to set initial values for the date in the model. On validating the form without opening datepicker, am getting validation error. However if i set the value using the datepicker or type in the date, no validation error is shown.

**Comment by ghiscoding** [comment]
Cannot help you without a Plunker, perhaps you can use this [Plunker example](http://plnkr.co/edit/ykWiwvOJbNvKYdVwXrhY?p=preview) which come from a previous issue #55 

If I try quickly with the plunker I just mentioned, and fix an original value, the validation works perfectly.
For example, put this valid date:
`vm.model.dateOfChange = '14/10/2015';`
And then try this invalid date:
`vm.model.dateOfChange = '14/10/2015';`

You can see the Error Validation Summary appears and disappears depending on what date you put in.

**Comment by ghiscoding** [comment]
If this is still an issue then please provide a Plunker so that I can understand your problem... else I will close the issue by the end of the week. Thanks

**Comment by ghiscoding** [comment]
No feedback provided... closing the issue
