### ISSUE TITLE
'strValue is not defined' error on string rules

### ISSUE THREAD

**Issue by eduardmartinez** [ghiscoding/angular-validation#78]
Hi.

I recently updated the package to 1.4.12 version and I have a rule for a field in this way:
```html
<input type='text' name='myField' validation='required|email|max:256' />
```
But this error appears: 
```
ReferenceError: strValue is not defined
```
I noticed it appears when the 'max:256' rule is applied and makes the 'email' rule fail because when I remove that rule, all works fine.

Thanks in advance.

**Comment by ghiscoding** [comment]
Hmm `max` is an auto-detect of the type, can you try to use the `max_len` or `max_num` depending on what you want and see if you get the error too. It would be nice to have a Plunker to debug it as well , if you could.

**Comment by eduardmartinez** [comment]
I tried with `max_len` and it worked. The problem is with `max`. I'll try to make a plunker anyway.

**Comment by eduardmartinez** [comment]
Here is the plunk: http://plnkr.co/edit/VWC0O6?p=preview

**Comment by ghiscoding** [comment]
Thanks for the Plunker, I'll take a look at it in the coming days. It's probably better for you to use the `max_len` in the mean time, and it's actually better since it doesn't have to auto-detect it every time with `max`.

**Comment by ghiscoding** [comment]
I actually found the issue, it's a small mistake of mine when I refactored my code. I'll push a revision to fix it maybe tomorrow.

**Comment by ghiscoding** [comment]
Quick fix so it's already done..thanks for feedback!

**Comment by eduardmartinez** [comment]
It works like a charm. Thank you!
