### ISSUE TITLE
Nothing working if translations fail to load with old angular-translate

### ISSUE THREAD

**Issue by shlomogoldstein** [ghiscoding/angular-validation#80]
I was using angular-translate 2.5.2 where loading static files using files: [] failed silently. Therefore this validation tool did not work at all, nor showed any errors...

**Comment by ghiscoding** [comment]
Does this old version support `$translate.instant(msg)` and does a regular `$translate(msg)` return a promise? If you answered NO to any of the 2 previous questions, then it explains the problem. Unless you provide a Plunker that we can troubleshoot with, I can't help you.

**Comment by ghiscoding** [comment]
I actually checked for the `$translate.instant(msg)` and `$translate(msg)` returning a promise. This was supported from version 2.2 and up, so that isn't your problem. 

If you want help then please provide a Plunker to troubleshoot. 
Thanks

**Comment by ghiscoding** [comment]
I need more details to investigate on that issue, else I will just close it. Please provide details on what you wrote exactly.

I'd like to close this issue at the same time I release my next version, which is coming very soon.

**Comment by shlomogoldstein** [comment]
You can close it, thank you
