### ISSUE TITLE
Custom error message

### ISSUE THREAD

**Issue by Jeevanandanj** [ghiscoding/angular-validation#84]
Angular validation is using default error message from the json file. Instead of that can we have custom error message for this with translate option.

I don't want to disturb the existing json file message, instead of can we have it in html attribute?

**Comment by ghiscoding** [comment]
You can use [Wiki - Alternate Message](https://github.com/ghiscoding/angular-validation/wiki/Alternate-Text-on-Validators)

And if you don't want to mix the angular-validation translation with your own translation, you should follow this [Wiki - HOWTO Step5. Configure the Angular-Translate Provider (JSON)](https://github.com/ghiscoding/angular-validation/wiki/HOWTO---Step-by-Step#step5)

All the information on how to use the library are in the Wikis, so make sure to read them first.

**Comment by ghiscoding** [comment]
If this is what you were looking for, then please close the open issue. 

And if you like the library, you could also click on the **Star** button... Thanks
