### ISSUE TITLE
Showing error in tooltip?

### ISSUE THREAD

**Issue by sandeepthomas** [ghiscoding/angular-validation#85]
Is there any way to show the errors in UI bootstrap tooltip ?

Thanks

**Comment by ghiscoding** [comment]
There's [Wiki - Validation Summary](https://github.com/ghiscoding/angular-validation/wiki/Validation-Summary) which contains and is used to display all errors. You could potentially use that to your advantage. 

So if you look at the Validation Summary example to display all the errors:
```html
<!-- Form Validation Summary -->
<div class="alert alert-danger alert-dismissable" ng-show="displayValidationSummary">
    <ul>
        <li ng-repeat="item in form1.$validationSummary">{{item.field }}: {{item.message}}</li>
    </ul>
</div>
```

You can see that all the errors exist inside the summary, you just need to find the one for your input. Let say you have a form named `myForm` an input named `input1`, you could potentially get the error by doing this: `myForm.$validationSummary.input1.message` or through a function:
```javascript
getInputError(inputName) {
    return myForm.$validatonSummary[inputName].message;
}
```

Try it out, I haven't tested it but it should work. If that answers your question, then please close the issue.

And if you like the library, you could also click on the **Star** button... Thanks

**Comment by sandeepthomas** [comment]
but how to attach the tooltip to the corresponding input?

**Comment by ghiscoding** [comment]
If you want to use UI Bootstrap Tooltip, it's your job to understand how to use it. My package is to provide validation and I also provided you a way to use it within your tooltip... how to use a Tooltip? That is up to you to find it.
