### ISSUE TITLE
Implicit global variable in validation-common.js

### ISSUE THREAD

**Issue by fasuke85** [ghiscoding/angular-validation#86]
Hi,
On line 994 and 1277, in validation-common.js you declare 
~~~~
regex = new RegExp(validator.pattern);
~~~~
and
~~~~
regex = new RegExp(validator.pattern, validator.patternFlag);
~~~~

respectively.  Is this an error, or is it actually ment to be this way?

Johannes

**Comment by ghiscoding** [comment]
Hello,

I could add it or leave it as is and nothing would change. The reason I use the `patternFlag` comes from the `validation-rules.js`, I specifially need to use it under these 2 validators: `in_list` and `not_in_list`. These 2 validators will always get called by the RegExp at line 1277 while at line 994 it's only used by Date validators which never use the `patternFlag`. 

So to resume again, I could add the `patternFlag` at line 994 to be more consistent in my code, but it wouldn't change anything to the end result.

Does that answer your question? Did you encounter any issues related to that flag?
Thanks for the feedback anyway :)

**Comment by fasuke85** [comment]
Ok, I probably could have been clearer :-)
My issue isn't with the flag, but the fact that regex isn't declared in the function, and is an implicit global variable. That creates som problems for me. So I'm just wondering if its a feature or a bug :-)

**Comment by ghiscoding** [comment]
Ah that's an error, they shouldn't be global. I just realized that when I refactored my code and made smaller functions; I forgot to redeclare the regex variable locally to each function. I could add the `var regex` to each function, rerun my protractor tests and push a new Revision if it's really a bug for you... let me know if it is.

**Comment by fasuke85** [comment]
That would be great, thanks :-)

**Comment by ghiscoding** [comment]
Ok I just finished with the changes and tests. Please try it out on new [Version 1.4.15](https://github.com/ghiscoding/angular-validation/releases/tag/v1.4.15)

I'll reopen it if you have more problems related to it, but it looks good on my end

If you like the package/library, you can also click on **Star** on top. Thanks :)
