### ISSUE TITLE
Bootstrap integration

### ISSUE THREAD

**Issue by nettino** [ghiscoding/angular-validation#88]
Is there a way I could toggle Bootstrap class 'has-error', 'has-feedback' (or 'has-success') for parent element (ie. div) of the invalid field with agular-validation library?

**Comment by ghiscoding** [comment]
I am not dealing at all with CSS class, Angular does it by itself when the field is valid/invalid it will add `.ng-valid` or `.ng-invalid`. You can see the CSS that I deal with in the sample with [style.css](https://github.com/ghiscoding/angular-validation/blob/master/style.css)

You could possibly use the `Validation-Callback` to do the wrapping yourself, depending if it's valid or invalid. So take a look at [Wiki - Validation-Callback](https://github.com/ghiscoding/angular-validation/wiki/Validation-Callback).

I basically won't do anything with the CSS from the library, you have to find a way to do it yourself... at least `Validation-Callback` seems like a good way to do it... Good luck.

**Comment by nettino** [comment]
I've quickly wrote simple decorator - in case someone needs that at any point:
```javascript
(function() {   
    
    var bootstrapValidationDecorator = function() {
		return {
			scope: {
				bootstrapValidationDecorator:'@'
			},
			restrict: 'A',
			require:  '^form',
			link: function (scope, el, attrs, formCtrl) {
				scope.form = formCtrl; // no template so no need for that for now
				console.log(scope.form);

				if(scope.bootstrapValidationDecorator!=undefined && scope.bootstrapValidationDecorator!="") {
					scope.fieldName = scope.bootstrapValidationDecorator;
				} else {		        	
		        	scope.fieldName = angular.element( el[0].querySelector("[name]") ).attr('name');
				}
          		
                scope.$watch(
                	function(scope) {
                		return (scope.form[scope.fieldName].$touched || scope.form.$submitted) && scope.form[scope.fieldName].$invalid;
                	},
                    function( newVal, oldVal ) {
                    	if(newVal != oldVal){
                    		el.toggleClass('has-error', newVal);
                    	}
                    }
                );
          		// TODO: need watch on expression: (formCtrl[inputName].$touched || formCtrl.$submitted) && formCtrl[inputName].$invalid)
  			}
    	}
    }
    angular.module('app').directive('bootstrapValidationDecorator', bootstrapValidationDecorator);

}());
```
Usage:
```html
<div class="form-group" bootstrap-validation-decorator>
    <label class="control-label">Your label</label>
    <input class="form-control" type="text" name="lastname" ng-model="user.lastname" validation="alpha_dash|min_len:2|max_len:50|required"  />
</div>
```
Name of the field must be declared.
You can also provide the field name:
```html
<div class="form-group" bootstrap-validation-decorator="lastname">
```

**Comment by ghiscoding** [comment]
Thanks for the demo, I could maybe add it in the list of Wiki documentation if that is useful. 

Also if you like my Angular-Validation package, you can click **Star** on top, that's all I ask :)

**Comment by ghiscoding** [comment]
Thanks for the demo, I added it in the Wiki list so that it might help others :)
See the [Wiki - Bootstrap Decorator (has-error)](https://github.com/ghiscoding/angular-validation/wiki/Bootstrap-Decorator-(has-error))

If you like my Angular-Validation package, you could also click **Star** on top, that's all I ask :)

**Comment by ghiscoding** [comment]
By the way, you said `Name of the field must be declared at all times.` but if I look at the first code sample under `Usage`, you're actually missing the name of the field, is that a mistake?

```html
<div class="form-group" bootstrap-validation-decorator>
    <label class="control-label">Your label</label>
    <input class="form-control" type="text" name="lastname" ng-model="user.lastname" validation="alpha_dash|min_len:2|max_len:50|required"  />
</div>
```

**Comment by nettino** [comment]
Hi, thanks for adding it to Wiki!
Name is declared on input: name="lastname" - maybe I should be more specific: Name of the **form** field must be declared at all times.

**Comment by ghiscoding** [comment]
Ok, I updated the Wiki. Thanks for the feedback.. enjoy the package ;)
