### ISSUE TITLE
Disappearing and blinking messages

### ISSUE THREAD

**Issue by nettino** [ghiscoding/angular-validation#90]
I'd like to have more control on displaying messages - specifically I don't want the error message to disappear once the user starts typing, only on model update - how can I achieve that?
Also I have noticed that sometimes messages are blinking (ie. on blur once the field is still invalid)...

**Comment by ghiscoding** [comment]
If you want to have the error message to display at all time, you could simply set the `debounce` to 0 (you can set it globally, see the [Wiki - Global Option](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) or as an attribute on each input)

Not sure to understand your blinking problem. Can you provide a Plunker or a print screen of that problem?

**Comment by nettino** [comment]
Hi. Thank you for prompt response. I don't really want to have debounce 0, just message changing or disappearing once user stop typing for a while and validation kicks off. At present it's dissappearing immediately on key press - do you know how to set it up?

For blinking you may try to just click on the field and click somewhere out of it while it's still invalid - then message disappears for a very short moment and appears again. Observed on Firefox for now (I haven't tried the other browsers). I may try to provide plunker tomorow if you're still unable to reproduce that.

**Comment by ghiscoding** [comment]
The Directive is built this way, that's the way I chose and I like so the core is built that way. You can't  really change this behavior apart from playing with the `debounce` like I mentioned. The only other feature you could try is Validation Summary, but it's probably not what you want. So at the end, you can't really change it...sorry.

For the blinking, I probably can't do anything about it either. The error messages are coming from Angular-Translate every time single time you do an action (in that case the onBlur event) and it also refreshes the `<span>` with the new error message (even if it's the same message) every single time, so basically I'm not surprised about the blinking. So unfortunately, Angular-Translate has a little delay to deal with and refreshing the HTML on top of that is making it worst.

**Comment by nettino** [comment]
That's too bad as I was planning to use it for a big application in here... Is there any way you could add the config option for that please?
I believe blinking would be gone with such option too.

**Comment by ghiscoding** [comment]
The blinking is fixed, I found a leftover 10ms in the onBlur event handler that I had forgot to remove when I was fixed another bug in the past.

As for your other behavior of displaying the error message while typing, it's really `debounce` that you should use. 

Since everything is done, I'm closing this issue.

**Comment by nettino** [comment]
Thank you for blinking fix! Any chance for not disappearing messages as an option?

**Comment by ghiscoding** [comment]
I told you, the `debounce` is the way to go.

**Comment by nettino** [comment]
OK - got it with debounce 0 as you said and ng-model-options="{ updateOn: 'default blur', debounce: { default: 1000, blur: 0 } }"  - thank you.

**Comment by ghiscoding** [comment]
I meant using the `debounce` from my Angular-Validation, not necessarily from `ngModel`. You can use `debounce` from the Angular-Validation [Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) 
```javascript
var vs = new validationService({ debounce: 0 });
```
 or as an attribute on each input) or from each input 
```javascript
<input name="input1" validation="required" debounce="0" />
```

I didn't think about using `debounce` from the `ngModel` but if it works, then I guess it's also good.
