### ISSUE TITLE
"." character in input name prevents error message from clearing

### ISSUE THREAD

**Issue by lwj5** [ghiscoding/angular-validation#92]
Possible solution to add to the list of dirty char.

var elmInputName = elmName.replace(/[.|&;$%@"<>()+,\[\]\{\}]/g, '');

Great package btw!

**Comment by ghiscoding** [comment]
I don't understand your issue, can you be a bit more specific of your problem and can you make a Plunker to test with.

**Comment by lwj5** [comment]
http://plnkr.co/edit/ArMzNELn9vKkWH9SErWQ

If the name attribute of the input field contains a DOT(.) char, the validation error messages will not be purged on input change.

Try clicking submit, or editing the input a few times and you will see.
