### ISSUE TITLE
Polish chars

### ISSUE THREAD

**Issue by Waniusza** [ghiscoding/angular-validation#94]
Hi! 
I tried to do it by pull request, but I failed without permissions:<

Can you add polish chars to your 'alpha' pattern?
It's 'ążźćśłńę' :)
It witth help many, and protect me from errors after update library :)

Thanks!

**Comment by ghiscoding** [comment]
Ok I will add it to all the `alpha` types, there's 5 of them (`alpha, alpha_spaces, ...`)

It might take couple days, I would like to push it at the same time I fix other open issues, so it will be part of the next revision by the end of this week.

Thanks for the feedback

**Comment by Waniusza** [comment]
That's great! :)
Thanks :)

**Comment by ghiscoding** [comment]
This was fixed in last release [v1.4.17](https://github.com/ghiscoding/angular-validation/releases/tag/v1.4.17)
