### ISSUE TITLE
in_list: doesn't work well with symbols

### ISSUE THREAD

**Issue by lwj5** [ghiscoding/angular-validation#96]
An example here: http://plnkr.co/edit/Rwupj91yWAbfgsgIebsb

Try to validate your blood type. "A" passes validation while, "A+" fails. Along with other text that have symbols. The feature seems to truncate symbols.

**Comment by ghiscoding** [comment]
I was using `\b` in my RegExp, which is Word Boundaries. This unfortunately means that only words are excepted, which excludes special characters and that explains why the `A` was valid while the `A+` was invalid.

I also found out that I don't actually need to use word boundaries, I can simply use it directly in my RegExp `^(word1|word2|A\+)$`, as long as the string is also escaped. 

I will push the fix in the next revision, sometime this week. Thanks for the feedback

You live in Singapore? It's nice there, been there twice, wouldn't mind to live there, better than Canadian winter hehe

**Comment by ghiscoding** [comment]
This was fixed in last release [v1.4.17](https://github.com/ghiscoding/angular-validation/releases/tag/v1.4.17)

**Comment by lwj5** [comment]
@ghiscoding I see, thanks for the really fast fix.

Yea, I live in Singapore! Canadian winter is just freezing cold, but It's gets pretty hot down here. For me, I would definitely like to go to a colder country! haha

I guess the grass is always greener on the other side eh. Cheers!

**Comment by ghiscoding** [comment]
Haha you're right, I don't mind the warm weather but I actually find that the humidity is a bit too high in Singapore. Canadian summer is nice, if only it could be all year haha. 

Thanks for the feedback, enjoy the package and tell your friends ;)
I'll let you know next time I go back to SG, hotel is near NUS university on Bencoolen street.
